/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.client.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserInfoEntity implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private String icon;
	private String phoneNumber;
	private int totalGain;
	private String nickName;
	private String userId;
	private int totalAssetValue;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the icon
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * @param icon the icon to set
	 */
	public void setIcon(String icon) {
		String old = this.icon;
		this.icon = icon;
		this.emitter.firePropertyChange("icon", old, this.icon);
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		String old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the totalGain
	 */
	public int getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(int totalGain) {
		int old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		String old = this.userId;
		this.userId = userId;
		this.emitter.firePropertyChange("userId", old, this.userId);
	}

	/**
	 * @return the totalAssetValue
	 */
	public int getTotalAssetValue() {
		return totalAssetValue;
	}

	/**
	 * @param totalAssetValue the totalAssetValue to set
	 */
	public void setTotalAssetValue(int totalAssetValue) {
		int old = this.totalAssetValue;
		this.totalAssetValue = totalAssetValue;
		this.emitter.firePropertyChange("totalAssetValue", old, this.totalAssetValue);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserInfoEntity ["+
                "icon=" + this.icon +
                " , phoneNumber=" + this.phoneNumber +
                " , totalGain=" + this.totalGain +
                " , nickName=" + this.nickName +
                " , userId=" + this.userId +
                " , totalAssetValue=" + this.totalAssetValue +
        "]";
    }	

}
