/* Generated By:JJTree: Do not edit this line. AstCompositeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstCompositeExpression extends SimpleNode {
  public AstCompositeExpression(int id) {
    super(id);
  }

  public AstCompositeExpression(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ede59d50d239f7efd9cb87a81d4d4928 (do not edit this line) */
