/* Generated By:JJTree: Do not edit this line. AstFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstFunction extends SimpleNode {
   protected String localName = "";

   protected String prefix = "";


   public AstFunction(int id) {
      super(id);
   }

   public AstFunction(ELParser p, int id) {
      super(p, id);
   }


   /** Accept the visitor. **/
   public Object jjtAccept(ELParserVisitor visitor, Object data) {
      return visitor.visit(this, data);
   }

   /**
    * Get the localName.
    * 
    * @return the localName.
    */
   public String getLocalName() {
      return localName;
   }

   /**
    * Get the prefix.
    * 
    * @return the prefix.
    */
   public String getPrefix() {
      return prefix;
   }

   /**
    * Set the localName.
    * 
    * @param localName The localName to set.
    */
   public void setLocalName(String localName) {
      this.localName = localName;
   }

   /**
    * Set the prefix.
    * 
    * @param prefix The prefix to set.
    */
   public void setPrefix(String prefix) {
      this.prefix = prefix;
   }
}
/* JavaCC - OriginalChecksum=e7ddee73e27e701b5e59da3f2ccb8f25 (do not edit this line) */
