/* Generated By:JJTree: Do not edit this line. AstGreaterThanEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstGreaterThanEqual extends SimpleNode {
  public AstGreaterThanEqual(int id) {
    super(id);
  }

  public AstGreaterThanEqual(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=15f4d6367701a52cce3665d97e9b47ce (do not edit this line) */
