/* Generated By:JJTree: Do not edit this line. AstGreaterThan.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstGreaterThan extends SimpleNode {
  public AstGreaterThan(int id) {
    super(id);
  }

  public AstGreaterThan(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e49c44adcf41b02a803ccc5b5a6ac886 (do not edit this line) */
