/* Generated By:JJTree: Do not edit this line. AstInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstInteger extends SimpleNode {
  public AstInteger(int id) {
    super(id);
  }

  public AstInteger(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() { return new StringBuffer(ELParserTreeConstants.jjtNodeName[id]).append('[').append(getImage()).append(']').toString(); }

}
/* JavaCC - OriginalChecksum=06391240ee1d19222e6dbbcb5f1f0dde (do not edit this line) */
