/* Generated By:JJTree: Do not edit this line. AstIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstIdentifier extends SimpleNode {
  public AstIdentifier(int id) {
    super(id);
  }

  public AstIdentifier(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() { return new StringBuffer(ELParserTreeConstants.jjtNodeName[id]).append('[').append(getImage()).append(']').toString(); }
}
/* JavaCC - OriginalChecksum=6617b6f576f77259bd111fd2e51905f9 (do not edit this line) */
