/* Generated By:JJTree: Do not edit this line. AstLiteralExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstLiteralExpression extends SimpleNode {
  public AstLiteralExpression(int id) {
    super(id);
  }

  public AstLiteralExpression(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7331ab53b5d3ac388f8e3cc1d60950b8 (do not edit this line) */
