/* Generated By:JJTree: Do not edit this line. AstLessThanEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstLessThanEqual extends SimpleNode {
  public AstLessThanEqual(int id) {
    super(id);
  }

  public AstLessThanEqual(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dccfa2fd42bd8284694618f79631e68e (do not edit this line) */
