/* Generated By:JJTree: Do not edit this line. AstMethodSuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstMethodSuffix extends SimpleNode {
  public AstMethodSuffix(int id) {
    super(id);
  }

  public AstMethodSuffix(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() { return new StringBuffer(ELParserTreeConstants.jjtNodeName[id]).append('[').append(getImage()).append("()]").toString(); }

}
/* JavaCC - OriginalChecksum=b692d43f1b307d31e9098bba5da8829d (do not edit this line) */
