/* Generated By:JJTree: Do not edit this line. AstPropertySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wxxr.mobile.el.parser;

public
class AstPropertySuffix extends SimpleNode {
  public AstPropertySuffix(int id) {
    super(id);
  }

  public AstPropertySuffix(ELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() { return new StringBuffer(ELParserTreeConstants.jjtNodeName[id]).append('[').append(getImage()).append(']').toString(); }

}
/* JavaCC - OriginalChecksum=b3a413c758b373b9930b566b4ccaf6f0 (do not edit this line) */
