/* Generated By:JavaCC: Do not edit this line. ELParserVisitor.java Version 5.0 */
package com.wxxr.mobile.el.parser;

public interface ELParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(AstCompositeExpression node, Object data);
  public Object visit(AstLiteralExpression node, Object data);
  public Object visit(AstDeferredExpression node, Object data);
  public Object visit(AstDynamicExpression node, Object data);
  public Object visit(AstChoice node, Object data);
  public Object visit(AstOr node, Object data);
  public Object visit(AstAnd node, Object data);
  public Object visit(AstEqual node, Object data);
  public Object visit(AstNotEqual node, Object data);
  public Object visit(AstLessThan node, Object data);
  public Object visit(AstGreaterThan node, Object data);
  public Object visit(AstLessThanEqual node, Object data);
  public Object visit(AstGreaterThanEqual node, Object data);
  public Object visit(AstPlus node, Object data);
  public Object visit(AstMinus node, Object data);
  public Object visit(AstMult node, Object data);
  public Object visit(AstDiv node, Object data);
  public Object visit(AstMod node, Object data);
  public Object visit(AstNegative node, Object data);
  public Object visit(AstNot node, Object data);
  public Object visit(AstEmpty node, Object data);
  public Object visit(AstValue node, Object data);
  public Object visit(AstPropertySuffix node, Object data);
  public Object visit(AstBracketSuffix node, Object data);
  public Object visit(AstMethodSuffix node, Object data);
  public Object visit(AstClosureSuffix node, Object data);
  public Object visit(AstClosure node, Object data);
  public Object visit(AstIdentifier node, Object data);
  public Object visit(AstFunction node, Object data);
  public Object visit(AstTrue node, Object data);
  public Object visit(AstFalse node, Object data);
  public Object visit(AstFloatingPoint node, Object data);
  public Object visit(AstInteger node, Object data);
  public Object visit(AstString node, Object data);
  public Object visit(AstNull node, Object data);
}
/* JavaCC - OriginalChecksum=cdc98f8b81058464b91b864ec5e81714 (do not edit this line) */
