/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.client.bean;

import java.util.List;
import com.wxxr.mobile.stock.client.model.TradingRecord;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class DealDetailBean implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private List<TradingRecord> tradingRecords;
	private String[] imgUrl;
	private String totalGain;
	private String userGain;
	private String fund;
	private String plRisk;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the tradingRecords
	 */
	public List<TradingRecord> getTradingRecords() {
		return tradingRecords;
	}

	/**
	 * @param tradingRecords the tradingRecords to set
	 */
	public void setTradingRecords(List<TradingRecord> tradingRecords) {
		List<TradingRecord> old = this.tradingRecords;
		this.tradingRecords = tradingRecords;
		this.emitter.firePropertyChange("tradingRecords", old, this.tradingRecords);
	}

	/**
	 * @return the imgUrl
	 */
	public String[] getImgUrl() {
		return imgUrl;
	}

	/**
	 * @param imgUrl the imgUrl to set
	 */
	public void setImgUrl(String[] imgUrl) {
		String[] old = this.imgUrl;
		this.imgUrl = imgUrl;
		this.emitter.firePropertyChange("imgUrl", old, this.imgUrl);
	}

	/**
	 * @return the totalGain
	 */
	public String getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(String totalGain) {
		String old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the userGain
	 */
	public String getUserGain() {
		return userGain;
	}

	/**
	 * @param userGain the userGain to set
	 */
	public void setUserGain(String userGain) {
		String old = this.userGain;
		this.userGain = userGain;
		this.emitter.firePropertyChange("userGain", old, this.userGain);
	}

	/**
	 * @return the fund
	 */
	public String getFund() {
		return fund;
	}

	/**
	 * @param fund the fund to set
	 */
	public void setFund(String fund) {
		String old = this.fund;
		this.fund = fund;
		this.emitter.firePropertyChange("fund", old, this.fund);
	}

	/**
	 * @return the plRisk
	 */
	public String getPlRisk() {
		return plRisk;
	}

	/**
	 * @param plRisk the plRisk to set
	 */
	public void setPlRisk(String plRisk) {
		String old = this.plRisk;
		this.plRisk = plRisk;
		this.emitter.firePropertyChange("plRisk", old, this.plRisk);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "DealDetailBean ["+
                "tradingRecords=" + this.tradingRecords +
                " , imgUrl=" + this.imgUrl +
                " , totalGain=" + this.totalGain +
                " , userGain=" + this.userGain +
                " , fund=" + this.fund +
                " , plRisk=" + this.plRisk +
        "]";
    }	

}
