/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.client.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class RegularTicketBean implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private int rankSeq;
	private long regular;
	private String nickName;
	private int gainCount;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the rankSeq
	 */
	public int getRankSeq() {
		return rankSeq;
	}

	/**
	 * @param rankSeq the rankSeq to set
	 */
	public void setRankSeq(int rankSeq) {
		int old = this.rankSeq;
		this.rankSeq = rankSeq;
		this.emitter.firePropertyChange("rankSeq", old, this.rankSeq);
	}

	/**
	 * @return the regular
	 */
	public long getRegular() {
		return regular;
	}

	/**
	 * @param regular the regular to set
	 */
	public void setRegular(long regular) {
		long old = this.regular;
		this.regular = regular;
		this.emitter.firePropertyChange("regular", old, this.regular);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the gainCount
	 */
	public int getGainCount() {
		return gainCount;
	}

	/**
	 * @param gainCount the gainCount to set
	 */
	public void setGainCount(int gainCount) {
		int old = this.gainCount;
		this.gainCount = gainCount;
		this.emitter.firePropertyChange("gainCount", old, this.gainCount);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "RegularTicketBean ["+
                "rankSeq=" + this.rankSeq +
                " , regular=" + this.regular +
                " , nickName=" + this.nickName +
                " , gainCount=" + this.gainCount +
        "]";
    }	

}
