/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.client.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserCreateTradAccInfoBean implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private float voucherCostRate;
	private String rateString;
	private String userId;
	private float depositRate;
	private Long maxAmount;
	private float capitalRate;
	private float costRate;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the voucherCostRate
	 */
	public float getVoucherCostRate() {
		return voucherCostRate;
	}

	/**
	 * @param voucherCostRate the voucherCostRate to set
	 */
	public void setVoucherCostRate(float voucherCostRate) {
		float old = this.voucherCostRate;
		this.voucherCostRate = voucherCostRate;
		this.emitter.firePropertyChange("voucherCostRate", old, this.voucherCostRate);
	}

	/**
	 * @return the rateString
	 */
	public String getRateString() {
		return rateString;
	}

	/**
	 * @param rateString the rateString to set
	 */
	public void setRateString(String rateString) {
		String old = this.rateString;
		this.rateString = rateString;
		this.emitter.firePropertyChange("rateString", old, this.rateString);
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		String old = this.userId;
		this.userId = userId;
		this.emitter.firePropertyChange("userId", old, this.userId);
	}

	/**
	 * @return the depositRate
	 */
	public float getDepositRate() {
		return depositRate;
	}

	/**
	 * @param depositRate the depositRate to set
	 */
	public void setDepositRate(float depositRate) {
		float old = this.depositRate;
		this.depositRate = depositRate;
		this.emitter.firePropertyChange("depositRate", old, this.depositRate);
	}

	/**
	 * @return the maxAmount
	 */
	public Long getMaxAmount() {
		return maxAmount;
	}

	/**
	 * @param maxAmount the maxAmount to set
	 */
	public void setMaxAmount(Long maxAmount) {
		Long old = this.maxAmount;
		this.maxAmount = maxAmount;
		this.emitter.firePropertyChange("maxAmount", old, this.maxAmount);
	}

	/**
	 * @return the capitalRate
	 */
	public float getCapitalRate() {
		return capitalRate;
	}

	/**
	 * @param capitalRate the capitalRate to set
	 */
	public void setCapitalRate(float capitalRate) {
		float old = this.capitalRate;
		this.capitalRate = capitalRate;
		this.emitter.firePropertyChange("capitalRate", old, this.capitalRate);
	}

	/**
	 * @return the costRate
	 */
	public float getCostRate() {
		return costRate;
	}

	/**
	 * @param costRate the costRate to set
	 */
	public void setCostRate(float costRate) {
		float old = this.costRate;
		this.costRate = costRate;
		this.emitter.firePropertyChange("costRate", old, this.costRate);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserCreateTradAccInfoBean ["+
                "voucherCostRate=" + this.voucherCostRate +
                " , rateString=" + this.rateString +
                " , userId=" + this.userId +
                " , depositRate=" + this.depositRate +
                " , maxAmount=" + this.maxAmount +
                " , capitalRate=" + this.capitalRate +
                " , costRate=" + this.costRate +
        "]";
    }	

}
