/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class AccountInfoBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String scoreBalance;
	private String balance;
	private List<ScoreBean> scores;
	private List<TradeDetailBean> tradeDetails;
	private String freeze;
	private String avalible;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the scoreBalance
	 */
	public String getScoreBalance() {
		return scoreBalance;
	}

	/**
	 * @param scoreBalance the scoreBalance to set
	 */
	public void setScoreBalance(String scoreBalance) {
		String old = this.scoreBalance;
		this.scoreBalance = scoreBalance;
		this.emitter.firePropertyChange("scoreBalance", old, this.scoreBalance);
	}

	/**
	 * @return the balance
	 */
	public String getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(String balance) {
		String old = this.balance;
		this.balance = balance;
		this.emitter.firePropertyChange("balance", old, this.balance);
	}

	/**
	 * @return the scores
	 */
	public List<ScoreBean> getScores() {
		return scores;
	}

	/**
	 * @param scores the scores to set
	 */
	public void setScores(List<ScoreBean> scores) {
		List<ScoreBean> old = this.scores;
		this.scores = scores;
		if(this.scores != null){
            this.scores = new ListDecorator<ScoreBean>("scores", this.emitter,this.scores);
        }
		this.emitter.firePropertyChange("scores", old, this.scores);
	}

	/**
	 * @return the tradeDetails
	 */
	public List<TradeDetailBean> getTradeDetails() {
		return tradeDetails;
	}

	/**
	 * @param tradeDetails the tradeDetails to set
	 */
	public void setTradeDetails(List<TradeDetailBean> tradeDetails) {
		List<TradeDetailBean> old = this.tradeDetails;
		this.tradeDetails = tradeDetails;
		if(this.tradeDetails != null){
            this.tradeDetails = new ListDecorator<TradeDetailBean>("tradeDetails", this.emitter,this.tradeDetails);
        }
		this.emitter.firePropertyChange("tradeDetails", old, this.tradeDetails);
	}

	/**
	 * @return the freeze
	 */
	public String getFreeze() {
		return freeze;
	}

	/**
	 * @param freeze the freeze to set
	 */
	public void setFreeze(String freeze) {
		String old = this.freeze;
		this.freeze = freeze;
		this.emitter.firePropertyChange("freeze", old, this.freeze);
	}

	/**
	 * @return the avalible
	 */
	public String getAvalible() {
		return avalible;
	}

	/**
	 * @param avalible the avalible to set
	 */
	public void setAvalible(String avalible) {
		String old = this.avalible;
		this.avalible = avalible;
		this.emitter.firePropertyChange("avalible", old, this.avalible);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "AccountInfoBean ["+
                "scoreBalance=" + this.scoreBalance +
                " , balance=" + this.balance +
                " , scores=" + this.scores +
                " , tradeDetails=" + this.tradeDetails +
                " , freeze=" + this.freeze +
                " , avalible=" + this.avalible +
        "]";
    }	

}
