/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class AccountInfoBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String scoreBalance;
	private String balance;
	private List<ScoreBean> scores;
	private List<TradeDetailBean> tradeDetails;
	private String freeze;
	private String avalible;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the scoreBalance
	 */
	public String getScoreBalance() {
		return scoreBalance;
	}

	/**
	 * @param scoreBalance the scoreBalance to set
	 */
	public void setScoreBalance(String scoreBalance) {
		String old = this.scoreBalance;
		this.scoreBalance = scoreBalance;
		this.emitter.firePropertyChange("scoreBalance", old, this.scoreBalance);
	}

	/**
	 * @return the balance
	 */
	public String getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(String balance) {
		String old = this.balance;
		this.balance = balance;
		this.emitter.firePropertyChange("balance", old, this.balance);
	}

	/**
	 * @return the scores
	 */
	public List<ScoreBean> getScores() {
		return scores;
	}

	/**
	 * @param scores the scores to set
	 */
	public void setScores(List<ScoreBean> scores) {
		List<ScoreBean> old = this.scores;
		this.scores = scores;
		if(this.scores != null){
            this.scores = new ListDecorator<ScoreBean>("scores", this.emitter,this.scores);
        }
		this.emitter.firePropertyChange("scores", old, this.scores);
	}

	/**
	 * @return the tradeDetails
	 */
	public List<TradeDetailBean> getTradeDetails() {
		return tradeDetails;
	}

	/**
	 * @param tradeDetails the tradeDetails to set
	 */
	public void setTradeDetails(List<TradeDetailBean> tradeDetails) {
		List<TradeDetailBean> old = this.tradeDetails;
		this.tradeDetails = tradeDetails;
		if(this.tradeDetails != null){
            this.tradeDetails = new ListDecorator<TradeDetailBean>("tradeDetails", this.emitter,this.tradeDetails);
        }
		this.emitter.firePropertyChange("tradeDetails", old, this.tradeDetails);
	}

	/**
	 * @return the freeze
	 */
	public String getFreeze() {
		return freeze;
	}

	/**
	 * @param freeze the freeze to set
	 */
	public void setFreeze(String freeze) {
		String old = this.freeze;
		this.freeze = freeze;
		this.emitter.firePropertyChange("freeze", old, this.freeze);
	}

	/**
	 * @return the avalible
	 */
	public String getAvalible() {
		return avalible;
	}

	/**
	 * @param avalible the avalible to set
	 */
	public void setAvalible(String avalible) {
		String old = this.avalible;
		this.avalible = avalible;
		this.emitter.firePropertyChange("avalible", old, this.avalible);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "AccountInfoBean ["+
                "scoreBalance=" + this.scoreBalance +
                " , balance=" + this.balance +
                " , scores=" + this.scores +
                " , tradeDetails=" + this.tradeDetails +
                " , freeze=" + this.freeze +
                " , avalible=" + this.avalible +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((avalible == null) ? 0 : avalible.hashCode());
		result = prime * result + ((balance == null) ? 0 : balance.hashCode());
		result = prime * result + ((freeze == null) ? 0 : freeze.hashCode());
		result = prime * result
				+ ((scoreBalance == null) ? 0 : scoreBalance.hashCode());
		result = prime * result + ((scores == null) ? 0 : scores.hashCode());
		result = prime * result
				+ ((tradeDetails == null) ? 0 : tradeDetails.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AccountInfoBean other = (AccountInfoBean) obj;
		if (avalible == null) {
			if (other.avalible != null)
				return false;
		} else if (!avalible.equals(other.avalible))
			return false;
		if (balance == null) {
			if (other.balance != null)
				return false;
		} else if (!balance.equals(other.balance))
			return false;
		if (freeze == null) {
			if (other.freeze != null)
				return false;
		} else if (!freeze.equals(other.freeze))
			return false;
		if (scoreBalance == null) {
			if (other.scoreBalance != null)
				return false;
		} else if (!scoreBalance.equals(other.scoreBalance))
			return false;
		if (scores == null) {
			if (other.scores != null)
				return false;
		} else if (!scores.equals(other.scores))
			return false;
		if (tradeDetails == null) {
			if (other.tradeDetails != null)
				return false;
		} else if (!tradeDetails.equals(other.tradeDetails))
			return false;
		return true;
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

}
