/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.Arrays;
import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class DealDetailBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<TradingRecordBean> tradingRecords;
	private List<String> imgUrl;
	private float totalGain;
	private float userGain;
	private String fund;
	private String plRisk;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the tradingRecords
	 */
	public List<TradingRecordBean> getTradingRecords() {
		return tradingRecords;
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

	/**
	 * @param tradingRecords the tradingRecords to set
	 */
	public void setTradingRecords(List<TradingRecordBean> tradingRecords) {
		List<TradingRecordBean> old = this.tradingRecords;
		this.tradingRecords = tradingRecords;
		if(this.tradingRecords != null){
            this.tradingRecords = new ListDecorator<TradingRecordBean>("tradingRecords", this.emitter,this.tradingRecords);
        }
		this.emitter.firePropertyChange("tradingRecords", old, this.tradingRecords);
	}

	/**
	 * @return the imgUrl
	 */
	public List<String> getImgUrl() {
		return imgUrl;
	}

	/**
	 * @param imgUrl the imgUrl to set
	 */
	public void setImgUrl(String[] imgUrl) {
		List<String> old = this.imgUrl;
		if(imgUrl!=null){
			this.imgUrl = Arrays.asList(imgUrl);
			this.emitter.firePropertyChange("imgUrl", old, this.imgUrl);
		}
	}

	/**
	 * @return the totalGain
	 */
	public float getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(float totalGain) {
		float old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the userGain
	 */
	public float getUserGain() {
		return userGain;
	}

	/**
	 * @param userGain the userGain to set
	 */
	public void setUserGain(float userGain) {
		float old = this.userGain;
		this.userGain = userGain;
		this.emitter.firePropertyChange("userGain", old, this.userGain);
	}

	/**
	 * @return the fund
	 */
	public String getFund() {
		return fund;
	}

	/**
	 * @param fund the fund to set
	 */
	public void setFund(String fund) {
		String old = this.fund;
		this.fund = fund;
		this.emitter.firePropertyChange("fund", old, this.fund);
	}

	/**
	 * @return the plRisk
	 */
	public String getPlRisk() {
		return plRisk;
	}

	/**
	 * @param plRisk the plRisk to set
	 */
	public void setPlRisk(String plRisk) {
	    String old = this.plRisk;
		this.plRisk = plRisk;
		this.emitter.firePropertyChange("plRisk", old, this.plRisk);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "DealDetailBean ["+
                "tradingRecords=" + this.tradingRecords +
                " , imgUrl=" + this.imgUrl +
                " , totalGain=" + this.totalGain +
                " , userGain=" + this.userGain +
                " , fund=" + this.fund +
                " , plRisk=" + this.plRisk +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fund == null) ? 0 : fund.hashCode());
		result = prime * result + ((imgUrl == null) ? 0 : imgUrl.hashCode());
		result = prime * result + ((plRisk == null) ? 0 : plRisk.hashCode());
		result = prime * result + Float.floatToIntBits(totalGain);
		result = prime * result
				+ ((tradingRecords == null) ? 0 : tradingRecords.hashCode());
		result = prime * result + Float.floatToIntBits(userGain);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DealDetailBean other = (DealDetailBean) obj;
		if (fund == null) {
			if (other.fund != null)
				return false;
		} else if (!fund.equals(other.fund))
			return false;
		if (imgUrl == null) {
			if (other.imgUrl != null)
				return false;
		} else if (!imgUrl.equals(other.imgUrl))
			return false;
		if (plRisk == null) {
			if (other.plRisk != null)
				return false;
		} else if (!plRisk.equals(other.plRisk))
			return false;
		if (Float.floatToIntBits(totalGain) != Float
				.floatToIntBits(other.totalGain))
			return false;
		if (tradingRecords == null) {
			if (other.tradingRecords != null)
				return false;
		} else if (!tradingRecords.equals(other.tradingRecords))
			return false;
		if (Float.floatToIntBits(userGain) != Float
				.floatToIntBits(other.userGain))
			return false;
		return true;
	}	

}
