/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class GainBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean virtual;
	private String maxStockCode;
	private String over;
	private String closeTime;
	private int status;
	private Long totalGain;
	private Long tradingAccountId;
	private String maxStockMarket;
	private Long sum;
	private Long userGain;
	private String maxStockName;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the virtual
	 */
	public boolean getVirtual() {
		return virtual;
	}

	/**
	 * @param virtual the virtual to set
	 */
	public void setVirtual(boolean virtual) {
		boolean old = this.virtual;
		this.virtual = virtual;
		this.emitter.firePropertyChange("virtual", old, this.virtual);
	}

	/**
	 * @return the maxStockCode
	 */
	public String getMaxStockCode() {
		return maxStockCode;
	}

	/**
	 * @param maxStockCode the maxStockCode to set
	 */
	public void setMaxStockCode(String maxStockCode) {
		String old = this.maxStockCode;
		this.maxStockCode = maxStockCode;
		this.emitter.firePropertyChange("maxStockCode", old, this.maxStockCode);
	}

	/**
	 * @return the over
	 */
	public String getOver() {
		return over;
	}

	/**
	 * @param over the over to set
	 */
	public void setOver(String over) {
		String old = this.over;
		this.over = over;
		this.emitter.firePropertyChange("over", old, this.over);
	}

	/**
	 * @return the closeTime
	 */
	public String getCloseTime() {
		return closeTime;
	}

	/**
	 * @param closeTime the closeTime to set
	 */
	public void setCloseTime(String closeTime) {
		String old = this.closeTime;
		this.closeTime = closeTime;
		this.emitter.firePropertyChange("closeTime", old, this.closeTime);
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(int status) {
		int old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the totalGain
	 */
	public Long getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(Long totalGain) {
		Long old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the tradingAccountId
	 */
	public Long getTradingAccountId() {
		return tradingAccountId;
	}

	/**
	 * @param tradingAccountId the tradingAccountId to set
	 */
	public void setTradingAccountId(Long tradingAccountId) {
		Long old = this.tradingAccountId;
		this.tradingAccountId = tradingAccountId;
		this.emitter.firePropertyChange("tradingAccountId", old, this.tradingAccountId);
	}

	/**
	 * @return the maxStockMarket
	 */
	public String getMaxStockMarket() {
		return maxStockMarket;
	}

	/**
	 * @param maxStockMarket the maxStockMarket to set
	 */
	public void setMaxStockMarket(String maxStockMarket) {
		String old = this.maxStockMarket;
		this.maxStockMarket = maxStockMarket;
		this.emitter.firePropertyChange("maxStockMarket", old, this.maxStockMarket);
	}

	/**
	 * @return the sum
	 */
	public Long getSum() {
		return sum;
	}

	/**
	 * @param sum the sum to set
	 */
	public void setSum(Long sum) {
		Long old = this.sum;
		this.sum = sum;
		this.emitter.firePropertyChange("sum", old, this.sum);
	}

	/**
	 * @return the userGain
	 */
	public Long getUserGain() {
		return userGain;
	}

	/**
	 * @param userGain the userGain to set
	 */
	public void setUserGain(Long userGain) {
		Long old = this.userGain;
		this.userGain = userGain;
		this.emitter.firePropertyChange("userGain", old, this.userGain);
	}

	/**
	 * @return the maxStockName
	 */
	public String getMaxStockName() {
		return maxStockName;
	}

	/**
	 * @param maxStockName the maxStockName to set
	 */
	public void setMaxStockName(String maxStockName) {
		String old = this.maxStockName;
		this.maxStockName = maxStockName;
		this.emitter.firePropertyChange("maxStockName", old, this.maxStockName);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "GainBean ["+
                "virtual=" + this.virtual +
                " , maxStockCode=" + this.maxStockCode +
                " , over=" + this.over +
                " , closeTime=" + this.closeTime +
                " , status=" + this.status +
                " , totalGain=" + this.totalGain +
                " , tradingAccountId=" + this.tradingAccountId +
                " , maxStockMarket=" + this.maxStockMarket +
                " , sum=" + this.sum +
                " , userGain=" + this.userGain +
                " , maxStockName=" + this.maxStockName +
        "]";
    }	

}
