/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MegagameRankBean implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private int rankSeq;
	private String maxStockCode;
	private String over;
	private Long totalGain;
	private int status;
	private String nickName;
	private String userId;
	private String maxStockMarket;
	private long acctID;
	private int gainRates;
	private String gainRate;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the rankSeq
	 */
	public int getRankSeq() {
		return rankSeq;
	}

	/**
	 * @param rankSeq the rankSeq to set
	 */
	public void setRankSeq(int rankSeq) {
		int old = this.rankSeq;
		this.rankSeq = rankSeq;
		this.emitter.firePropertyChange("rankSeq", old, this.rankSeq);
	}

	/**
	 * @return the maxStockCode
	 */
	public String getMaxStockCode() {
		return maxStockCode;
	}

	/**
	 * @param maxStockCode the maxStockCode to set
	 */
	public void setMaxStockCode(String maxStockCode) {
		String old = this.maxStockCode;
		this.maxStockCode = maxStockCode;
		this.emitter.firePropertyChange("maxStockCode", old, this.maxStockCode);
	}

	/**
	 * @return the over
	 */
	public String getOver() {
		return over;
	}

	/**
	 * @param over the over to set
	 */
	public void setOver(String over) {
		String old = this.over;
		this.over = over;
		this.emitter.firePropertyChange("over", old, this.over);
	}

	/**
	 * @return the totalGain
	 */
	public Long getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(Long totalGain) {
		Long old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(int status) {
		int old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		String old = this.userId;
		this.userId = userId;
		this.emitter.firePropertyChange("userId", old, this.userId);
	}

	/**
	 * @return the maxStockMarket
	 */
	public String getMaxStockMarket() {
		return maxStockMarket;
	}

	/**
	 * @param maxStockMarket the maxStockMarket to set
	 */
	public void setMaxStockMarket(String maxStockMarket) {
		String old = this.maxStockMarket;
		this.maxStockMarket = maxStockMarket;
		this.emitter.firePropertyChange("maxStockMarket", old, this.maxStockMarket);
	}

	/**
	 * @return the acctID
	 */
	public long getAcctID() {
		return acctID;
	}

	/**
	 * @param acctID the acctID to set
	 */
	public void setAcctID(long acctID) {
		long old = this.acctID;
		this.acctID = acctID;
		this.emitter.firePropertyChange("acctID", old, this.acctID);
	}

	/**
	 * @return the gainRates
	 */
	public int getGainRates() {
		return gainRates;
	}

	/**
	 * @param gainRates the gainRates to set
	 */
	public void setGainRates(int gainRates) {
		int old = this.gainRates;
		this.gainRates = gainRates;
		this.emitter.firePropertyChange("gainRates", old, this.gainRates);
	}

	/**
	 * @return the gainRate
	 */
	public String getGainRate() {
		return gainRate;
	}

	/**
	 * @param gainRate the gainRate to set
	 */
	public void setGainRate(String gainRate) {
		String old = this.gainRate;
		this.gainRate = gainRate;
		this.emitter.firePropertyChange("gainRate", old, this.gainRate);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MegagameRankBean ["+
                "rankSeq=" + this.rankSeq +
                " , maxStockCode=" + this.maxStockCode +
                " , over=" + this.over +
                " , totalGain=" + this.totalGain +
                " , status=" + this.status +
                " , nickName=" + this.nickName +
                " , userId=" + this.userId +
                " , maxStockMarket=" + this.maxStockMarket +
                " , acctID=" + this.acctID +
                " , gainRates=" + this.gainRates +
                " , gainRate=" + this.gainRate +
        "]";
    }	

}
