/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MegagameRankBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private int rankSeq;
	private String maxStockCode;
	private String over;
	private Long totalGain;
	private int status;
	private String nickName;
	private String userId;
	private String maxStockMarket;
	private long acctID;
	private int gainRates;
	private String gainRate;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	



	/**
	 * @return the rankSeq
	 */
	public int getRankSeq() {
		return rankSeq;
	}

	/**
	 * @param rankSeq the rankSeq to set
	 */
	public void setRankSeq(int rankSeq) {
		int old = this.rankSeq;
		this.rankSeq = rankSeq;
		this.emitter.firePropertyChange("rankSeq", old, this.rankSeq);
	}

	/**
	 * @return the maxStockCode
	 */
	public String getMaxStockCode() {
		return maxStockCode;
	}

	/**
	 * @param maxStockCode the maxStockCode to set
	 */
	public void setMaxStockCode(String maxStockCode) {
		String old = this.maxStockCode;
		this.maxStockCode = maxStockCode;
		this.emitter.firePropertyChange("maxStockCode", old, this.maxStockCode);
	}

	/**
	 * @return the over
	 */
	public String getOver() {
		return over;
	}

	/**
	 * @param over the over to set
	 */
	public void setOver(String over) {
		String old = this.over;
		this.over = over;
		this.emitter.firePropertyChange("over", old, this.over);
	}

	/**
	 * @return the totalGain
	 */
	public Long getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(Long totalGain) {
		Long old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(int status) {
		int old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		String old = this.userId;
		this.userId = userId;
		this.emitter.firePropertyChange("userId", old, this.userId);
	}

	/**
	 * @return the maxStockMarket
	 */
	public String getMaxStockMarket() {
		return maxStockMarket;
	}

	/**
	 * @param maxStockMarket the maxStockMarket to set
	 */
	public void setMaxStockMarket(String maxStockMarket) {
		String old = this.maxStockMarket;
		this.maxStockMarket = maxStockMarket;
		this.emitter.firePropertyChange("maxStockMarket", old, this.maxStockMarket);
	}

	/**
	 * @return the acctID
	 */
	public long getAcctID() {
		return acctID;
	}

	/**
	 * @param acctID the acctID to set
	 */
	public void setAcctID(long acctID) {
		long old = this.acctID;
		this.acctID = acctID;
		this.emitter.firePropertyChange("acctID", old, this.acctID);
	}

	/**
	 * @return the gainRates
	 */
	public int getGainRates() {
		return gainRates;
	}

	/**
	 * @param gainRates the gainRates to set
	 */
	public void setGainRates(int gainRates) {
		int old = this.gainRates;
		this.gainRates = gainRates;
		this.emitter.firePropertyChange("gainRates", old, this.gainRates);
	}

	/**
	 * @return the gainRate
	 */
	public String getGainRate() {
		return gainRate;
	}

	/**
	 * @param gainRate the gainRate to set
	 */
	public void setGainRate(String gainRate) {
		String old = this.gainRate;
		this.gainRate = gainRate;
		this.emitter.firePropertyChange("gainRate", old, this.gainRate);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MegagameRankBean ["+
                "rankSeq=" + this.rankSeq +
                " , maxStockCode=" + this.maxStockCode +
                " , over=" + this.over +
                " , totalGain=" + this.totalGain +
                " , status=" + this.status +
                " , nickName=" + this.nickName +
                " , userId=" + this.userId +
                " , maxStockMarket=" + this.maxStockMarket +
                " , acctID=" + this.acctID +
                " , gainRates=" + this.gainRates +
                " , gainRate=" + this.gainRate +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (acctID ^ (acctID >>> 32));
		result = prime * result
				+ ((gainRate == null) ? 0 : gainRate.hashCode());
		result = prime * result + gainRates;
		result = prime * result
				+ ((maxStockCode == null) ? 0 : maxStockCode.hashCode());
		result = prime * result
				+ ((maxStockMarket == null) ? 0 : maxStockMarket.hashCode());
		result = prime * result
				+ ((nickName == null) ? 0 : nickName.hashCode());
		result = prime * result + ((over == null) ? 0 : over.hashCode());
		result = prime * result + rankSeq;
		result = prime * result + status;
		result = prime * result
				+ ((totalGain == null) ? 0 : totalGain.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MegagameRankBean other = (MegagameRankBean) obj;
		if (acctID != other.acctID)
			return false;
		if (gainRate == null) {
			if (other.gainRate != null)
				return false;
		} else if (!gainRate.equals(other.gainRate))
			return false;
		if (gainRates != other.gainRates)
			return false;
		if (maxStockCode == null) {
			if (other.maxStockCode != null)
				return false;
		} else if (!maxStockCode.equals(other.maxStockCode))
			return false;
		if (maxStockMarket == null) {
			if (other.maxStockMarket != null)
				return false;
		} else if (!maxStockMarket.equals(other.maxStockMarket))
			return false;
		if (nickName == null) {
			if (other.nickName != null)
				return false;
		} else if (!nickName.equals(other.nickName))
			return false;
		if (over == null) {
			if (other.over != null)
				return false;
		} else if (!over.equals(other.over))
			return false;
		if (rankSeq != other.rankSeq)
			return false;
		if (status != other.status)
			return false;
		if (totalGain == null) {
			if (other.totalGain != null)
				return false;
		} else if (!totalGain.equals(other.totalGain))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}	

}
