/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MessageInfoListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<MessageInfoBean> messageInfos;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	


	/**
	 * @return the messageInfos
	 */
	public List<MessageInfoBean> getMessageInfos() {
		return messageInfos;
	}

	/**
	 * @param messageInfos the messageInfos to set
	 */
	public void setMessageInfos(List<MessageInfoBean> messageInfos) {
		List<MessageInfoBean> old = this.messageInfos;
		this.messageInfos = messageInfos;
		if(this.messageInfos != null){
            this.messageInfos = new ListDecorator<MessageInfoBean>("messageInfos", this.emitter,this.messageInfos);
        }
		this.emitter.firePropertyChange("messageInfos", old, this.messageInfos);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MessageInfoListBean ["+
                "messageInfos=" + this.messageInfos +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((messageInfos == null) ? 0 : messageInfos.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MessageInfoListBean other = (MessageInfoListBean) obj;
		if (messageInfos == null) {
			if (other.messageInfos != null)
				return false;
		} else if (!messageInfos.equals(other.messageInfos))
			return false;
		return true;
	}	

}
