/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MessageInfoListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<MessageInfoBean> messageInfos;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the messageInfos
	 */
	public List<MessageInfoBean> getMessageInfos() {
		return messageInfos;
	}

	/**
	 * @param messageInfos the messageInfos to set
	 */
	public void setMessageInfos(List<MessageInfoBean> messageInfos) {
		List<MessageInfoBean> old = this.messageInfos;
		this.messageInfos = messageInfos;
		if(this.messageInfos != null){
            this.messageInfos = new ListDecorator<MessageInfoBean>("messageInfos", this.emitter,this.messageInfos);
        }
		this.emitter.firePropertyChange("messageInfos", old, this.messageInfos);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MessageInfoListBean ["+
                "messageInfos=" + this.messageInfos +
        "]";
    }	

}
