/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MyArticlesBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<ArticleBean> helpArticles;
	private List<ArticleBean> homeArticles;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	


	/**
	 * @return the helpArticles
	 */
	public List<ArticleBean> getHelpArticles() {
		return helpArticles;
	}

	/**
	 * @param helpArticles the helpArticles to set
	 */
	public void setHelpArticles(List<ArticleBean> helpArticles) {
		List<ArticleBean> old = this.helpArticles;
		this.helpArticles = helpArticles;
		if(this.helpArticles != null){
            this.helpArticles = new ListDecorator<ArticleBean>("helpArticles", this.emitter,this.helpArticles);
        }
		this.emitter.firePropertyChange("helpArticles", old, this.helpArticles);
	}

	/**
	 * @return the homeArticles
	 */
	public List<ArticleBean> getHomeArticles() {
		return homeArticles;
	}

	/**
	 * @param homeArticles the homeArticles to set
	 */
	public void setHomeArticles(List<ArticleBean> homeArticles) {
		List<ArticleBean> old = this.homeArticles;
		this.homeArticles = homeArticles;
		if(this.homeArticles != null){
            this.homeArticles = new ListDecorator<ArticleBean>("homeArticles", this.emitter,this.homeArticles);
        }
		this.emitter.firePropertyChange("homeArticles", old, this.homeArticles);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MyArticlesBean ["+
                "helpArticles=" + this.helpArticles +
                " , homeArticles=" + this.homeArticles +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((helpArticles == null) ? 0 : helpArticles.hashCode());
		result = prime * result
				+ ((homeArticles == null) ? 0 : homeArticles.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MyArticlesBean other = (MyArticlesBean) obj;
		if (helpArticles == null) {
			if (other.helpArticles != null)
				return false;
		} else if (!helpArticles.equals(other.helpArticles))
			return false;
		if (homeArticles == null) {
			if (other.homeArticles != null)
				return false;
		} else if (!homeArticles.equals(other.homeArticles))
			return false;
		return true;
	}	

}
