/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class QuotationListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private StockQuotationBean shBean;
	private List<StockQuotationBean> list;
	private StockQuotationBean szBean;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}


	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

	/**
	 * @return the shBean
	 */
	public StockQuotationBean getShBean() {
		return shBean;
	}

	/**
	 * @param shBean the shBean to set
	 */
	public void setShBean(StockQuotationBean shBean) {
		StockQuotationBean old = this.shBean;
		this.shBean = shBean;
		this.emitter.firePropertyChange("shBean", old, this.shBean);
	}

	/**
	 * @return the list
	 */
	public List<StockQuotationBean> getList() {
		return list;
	}

	/**
	 * @param list the list to set
	 */
	public void setList(List<StockQuotationBean> list) {
		List<StockQuotationBean> old = this.list;
		this.list = list;
		if(this.list != null){
            this.list = new ListDecorator<StockQuotationBean>("list", this.emitter,this.list);
        }
		this.emitter.firePropertyChange("list", old, this.list);
	}

	/**
	 * @return the szBean
	 */
	public StockQuotationBean getSzBean() {
		return szBean;
	}

	/**
	 * @param szBean the szBean to set
	 */
	public void setSzBean(StockQuotationBean szBean) {
		StockQuotationBean old = this.szBean;
		this.szBean = szBean;
		this.emitter.firePropertyChange("szBean", old, this.szBean);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "QuotationListBean ["+
                "shBean=" + this.shBean +
                " , list=" + this.list +
                " , szBean=" + this.szBean +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((list == null) ? 0 : list.hashCode());
		result = prime * result + ((shBean == null) ? 0 : shBean.hashCode());
		result = prime * result + ((szBean == null) ? 0 : szBean.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QuotationListBean other = (QuotationListBean) obj;
		if (list == null) {
			if (other.list != null)
				return false;
		} else if (!list.equals(other.list))
			return false;
		if (shBean == null) {
			if (other.shBean != null)
				return false;
		} else if (!shBean.equals(other.shBean))
			return false;
		if (szBean == null) {
			if (other.szBean != null)
				return false;
		} else if (!szBean.equals(other.szBean))
			return false;
		return true;
	}	

}
