/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class RankListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<MegagameRankBean> tRankBeans;
	private List<MegagameRankBean> t1RankBeans;
	private List<EarnRankItemBean> earnRankBeans;
	private List<WeekRankBean> weekRanKBeans;
	private List<RegularTicketBean> regularTicketBeans;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the tRankBeans
	 */
	public List<MegagameRankBean> getTRankBeans() {
		return tRankBeans;
	}

	/**
	 * @param tRankBeans the tRankBeans to set
	 */
	public void setTRankBeans(List<MegagameRankBean> tRankBeans) {
		List<MegagameRankBean> old = this.tRankBeans;
		this.tRankBeans = tRankBeans;
		if(this.tRankBeans != null){
            this.tRankBeans = new ListDecorator<MegagameRankBean>("tRankBeans", this.emitter,this.tRankBeans);
        }
		this.emitter.firePropertyChange("tRankBeans", old, this.tRankBeans);
	}

	/**
	 * @return the t1RankBeans
	 */
	public List<MegagameRankBean> getT1RankBeans() {
		return t1RankBeans;
	}

	/**
	 * @param t1RankBeans the t1RankBeans to set
	 */
	public void setT1RankBeans(List<MegagameRankBean> t1RankBeans) {
		List<MegagameRankBean> old = this.t1RankBeans;
		this.t1RankBeans = t1RankBeans;
		if(this.t1RankBeans != null){
            this.t1RankBeans = new ListDecorator<MegagameRankBean>("t1RankBeans", this.emitter,this.t1RankBeans);
        }
		this.emitter.firePropertyChange("t1RankBeans", old, this.t1RankBeans);
	}

	/**
	 * @return the earnRankBeans
	 */
	public List<EarnRankItemBean> getEarnRankBeans() {
		return earnRankBeans;
	}

	/**
	 * @param earnRankBeans the earnRankBeans to set
	 */
	public void setEarnRankBeans(List<EarnRankItemBean> earnRankBeans) {
		List<EarnRankItemBean> old = this.earnRankBeans;
		this.earnRankBeans = earnRankBeans;
		if(this.earnRankBeans != null){
            this.earnRankBeans = new ListDecorator<EarnRankItemBean>("earnRankBeans", this.emitter,this.earnRankBeans);
        }
		this.emitter.firePropertyChange("earnRankBeans", old, this.earnRankBeans);
	}

	/**
	 * @return the weekRanKBeans
	 */
	public List<WeekRankBean> getWeekRanKBeans() {
		return weekRanKBeans;
	}

	/**
	 * @param weekRanKBeans the weekRanKBeans to set
	 */
	public void setWeekRanKBeans(List<WeekRankBean> weekRanKBeans) {
		List<WeekRankBean> old = this.weekRanKBeans;
		this.weekRanKBeans = weekRanKBeans;
		if(this.weekRanKBeans != null){
            this.weekRanKBeans = new ListDecorator<WeekRankBean>("weekRanKBeans", this.emitter,this.weekRanKBeans);
        }
		this.emitter.firePropertyChange("weekRanKBeans", old, this.weekRanKBeans);
	}

	/**
	 * @return the regularTicketBeans
	 */
	public List<RegularTicketBean> getRegularTicketBeans() {
		return regularTicketBeans;
	}

	/**
	 * @param regularTicketBeans the regularTicketBeans to set
	 */
	public void setRegularTicketBeans(List<RegularTicketBean> regularTicketBeans) {
		List<RegularTicketBean> old = this.regularTicketBeans;
		this.regularTicketBeans = regularTicketBeans;
		if(this.regularTicketBeans != null){
            this.regularTicketBeans = new ListDecorator<RegularTicketBean>("regularTicketBeans", this.emitter,this.regularTicketBeans);
        }
		this.emitter.firePropertyChange("regularTicketBeans", old, this.regularTicketBeans);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "RankListBean ["+
                "tRankBeans=" + this.tRankBeans +
                " , t1RankBeans=" + this.t1RankBeans +
                " , earnRankBeans=" + this.earnRankBeans +
                " , weekRanKBeans=" + this.weekRanKBeans +
                " , regularTicketBeans=" + this.regularTicketBeans +
        "]";
    }	

}
