/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class RegularTicketBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private int rankSeq;
	private long regular;
	private String nickName;
	private int gainCount;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the rankSeq
	 */
	public int getRankSeq() {
		return rankSeq;
	}

	/**
	 * @param rankSeq the rankSeq to set
	 */
	public void setRankSeq(int rankSeq) {
		int old = this.rankSeq;
		this.rankSeq = rankSeq;
		this.emitter.firePropertyChange("rankSeq", old, this.rankSeq);
	}

	/**
	 * @return the regular
	 */
	public long getRegular() {
		return regular;
	}

	/**
	 * @param regular the regular to set
	 */
	public void setRegular(long regular) {
		long old = this.regular;
		this.regular = regular;
		this.emitter.firePropertyChange("regular", old, this.regular);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the gainCount
	 */
	public int getGainCount() {
		return gainCount;
	}

	/**
	 * @param gainCount the gainCount to set
	 */
	public void setGainCount(int gainCount) {
		int old = this.gainCount;
		this.gainCount = gainCount;
		this.emitter.firePropertyChange("gainCount", old, this.gainCount);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "RegularTicketBean ["+
                "rankSeq=" + this.rankSeq +
                " , regular=" + this.regular +
                " , nickName=" + this.nickName +
                " , gainCount=" + this.gainCount +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + gainCount;
		result = prime * result
				+ ((nickName == null) ? 0 : nickName.hashCode());
		result = prime * result + rankSeq;
		result = prime * result + (int) (regular ^ (regular >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RegularTicketBean other = (RegularTicketBean) obj;
		if (gainCount != other.gainCount)
			return false;
		if (nickName == null) {
			if (other.nickName != null)
				return false;
		} else if (!nickName.equals(other.nickName))
			return false;
		if (rankSeq != other.rankSeq)
			return false;
		if (regular != other.regular)
			return false;
		return true;
	}	

}
