/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class ScoreInfoBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String balance;
	private List<ScoreBean> scores;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the balance
	 */
	public String getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(String balance) {
		String old = this.balance;
		this.balance = balance;
		this.emitter.firePropertyChange("balance", old, this.balance);
	}

	/**
	 * @return the scores
	 */
	public List<ScoreBean> getScores() {
		return scores;
	}

	/**
	 * @param scores the scores to set
	 */
	public void setScores(List<ScoreBean> scores) {
		List<ScoreBean> old = this.scores;
		this.scores = scores;
		if(this.scores != null){
            this.scores = new ListDecorator<ScoreBean>("scores", this.emitter,this.scores);
        }
		this.emitter.firePropertyChange("scores", old, this.scores);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "ScoreInfoBean ["+
                "balance=" + this.balance +
                " , scores=" + this.scores +
        "]";
    }	

}
