/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.stock.info.mtree.sync.bean.StockBaseInfo;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class SearchStockListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<StockBaseInfo> searchResult;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the searchResult
	 */
	public List<StockBaseInfo> getSearchResult() {
		return searchResult;
	}

	/**
	 * @param searchResult the searchResult to set
	 */
	public void setSearchResult(List<StockBaseInfo> searchResult) {
		List<StockBaseInfo> old = this.searchResult;
		this.searchResult = searchResult;
		if(this.searchResult != null){
            this.searchResult = new ListDecorator<StockBaseInfo>("searchResult", this.emitter,this.searchResult);
        }
		this.emitter.firePropertyChange("searchResult", old, this.searchResult);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "SearchStockListBean ["+
                "searchResult=" + this.searchResult +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((searchResult == null) ? 0 : searchResult.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SearchStockListBean other = (SearchStockListBean) obj;
		if (searchResult == null) {
			if (other.searchResult != null)
				return false;
		} else if (!searchResult.equals(other.searchResult))
			return false;
		return true;
	}	

}
