/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class StockQuotationBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private Long risefallrate;
	private Long change;
	private Long szjs;
	private Long buysum;
	private Long secuvolume;
	private Long capital;
	private Long close;
	private Long profitrate;
	private Long open;
	private Long sellsum;
	private String datetime;
	private Long sellvolume2;
	private Long sellvolume3;
	private Long buyprice2;
	private Long sellvolume1;
	private Long buyprice1;
	private Long marketvalue;
	private Long status;
	private String code;
	private Long averageprice;
	private Long sellvolume4;
	private Long sellvolume5;
	private Long handrate;
	private Long ppjs;
	private String market;
	private Long sellprice5;
	private Long xdjs;
	private Long sellprice3;
	private Long buyvolume4;
	private Long newprice;
	private Long sellprice4;
	private Long buyvolume5;
	private Long lb;
	private Long secuamount;
	private Long high;
	private Long sellprice1;
	private Long low;
	private Long buyprice3;
	private Long buyvolume2;
	private Long sellprice2;
	private Long buyprice4;
	private Long buyvolume3;
	private Long buyprice5;
	private Long buyvolume1;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the risefallrate
	 */
	public Long getRisefallrate() {
		return risefallrate;
	}

	/**
	 * @param risefallrate the risefallrate to set
	 */
	public void setRisefallrate(Long risefallrate) {
		Long old = this.risefallrate;
		this.risefallrate = risefallrate;
		this.emitter.firePropertyChange("risefallrate", old, this.risefallrate);
	}

	/**
	 * @return the change
	 */
	public Long getChange() {
		return change;
	}

	/**
	 * @param change the change to set
	 */
	public void setChange(Long change) {
		Long old = this.change;
		this.change = change;
		this.emitter.firePropertyChange("change", old, this.change);
	}

	/**
	 * @return the szjs
	 */
	public Long getSzjs() {
		return szjs;
	}

	/**
	 * @param szjs the szjs to set
	 */
	public void setSzjs(Long szjs) {
		Long old = this.szjs;
		this.szjs = szjs;
		this.emitter.firePropertyChange("szjs", old, this.szjs);
	}

	/**
	 * @return the buysum
	 */
	public Long getBuysum() {
		return buysum;
	}

	/**
	 * @param buysum the buysum to set
	 */
	public void setBuysum(Long buysum) {
		Long old = this.buysum;
		this.buysum = buysum;
		this.emitter.firePropertyChange("buysum", old, this.buysum);
	}

	/**
	 * @return the secuvolume
	 */
	public Long getSecuvolume() {
		return secuvolume;
	}

	/**
	 * @param secuvolume the secuvolume to set
	 */
	public void setSecuvolume(Long secuvolume) {
		Long old = this.secuvolume;
		this.secuvolume = secuvolume;
		this.emitter.firePropertyChange("secuvolume", old, this.secuvolume);
	}

	/**
	 * @return the capital
	 */
	public Long getCapital() {
		return capital;
	}

	/**
	 * @param capital the capital to set
	 */
	public void setCapital(Long capital) {
		Long old = this.capital;
		this.capital = capital;
		this.emitter.firePropertyChange("capital", old, this.capital);
	}

	/**
	 * @return the close
	 */
	public Long getClose() {
		return close;
	}

	/**
	 * @param close the close to set
	 */
	public void setClose(Long close) {
		Long old = this.close;
		this.close = close;
		this.emitter.firePropertyChange("close", old, this.close);
	}

	/**
	 * @return the profitrate
	 */
	public Long getProfitrate() {
		return profitrate;
	}

	/**
	 * @param profitrate the profitrate to set
	 */
	public void setProfitrate(Long profitrate) {
		Long old = this.profitrate;
		this.profitrate = profitrate;
		this.emitter.firePropertyChange("profitrate", old, this.profitrate);
	}

	/**
	 * @return the open
	 */
	public Long getOpen() {
		return open;
	}

	/**
	 * @param open the open to set
	 */
	public void setOpen(Long open) {
		Long old = this.open;
		this.open = open;
		this.emitter.firePropertyChange("open", old, this.open);
	}

	/**
	 * @return the sellsum
	 */
	public Long getSellsum() {
		return sellsum;
	}

	/**
	 * @param sellsum the sellsum to set
	 */
	public void setSellsum(Long sellsum) {
		Long old = this.sellsum;
		this.sellsum = sellsum;
		this.emitter.firePropertyChange("sellsum", old, this.sellsum);
	}

	/**
	 * @return the datetime
	 */
	public String getDatetime() {
		return datetime;
	}

	/**
	 * @param datetime the datetime to set
	 */
	public void setDatetime(String datetime) {
		String old = this.datetime;
		this.datetime = datetime;
		this.emitter.firePropertyChange("datetime", old, this.datetime);
	}

	/**
	 * @return the sellvolume2
	 */
	public Long getSellvolume2() {
		return sellvolume2;
	}

	/**
	 * @param sellvolume2 the sellvolume2 to set
	 */
	public void setSellvolume2(Long sellvolume2) {
		Long old = this.sellvolume2;
		this.sellvolume2 = sellvolume2;
		this.emitter.firePropertyChange("sellvolume2", old, this.sellvolume2);
	}

	/**
	 * @return the sellvolume3
	 */
	public Long getSellvolume3() {
		return sellvolume3;
	}

	/**
	 * @param sellvolume3 the sellvolume3 to set
	 */
	public void setSellvolume3(Long sellvolume3) {
		Long old = this.sellvolume3;
		this.sellvolume3 = sellvolume3;
		this.emitter.firePropertyChange("sellvolume3", old, this.sellvolume3);
	}

	/**
	 * @return the buyprice2
	 */
	public Long getBuyprice2() {
		return buyprice2;
	}

	/**
	 * @param buyprice2 the buyprice2 to set
	 */
	public void setBuyprice2(Long buyprice2) {
		Long old = this.buyprice2;
		this.buyprice2 = buyprice2;
		this.emitter.firePropertyChange("buyprice2", old, this.buyprice2);
	}

	/**
	 * @return the sellvolume1
	 */
	public Long getSellvolume1() {
		return sellvolume1;
	}

	/**
	 * @param sellvolume1 the sellvolume1 to set
	 */
	public void setSellvolume1(Long sellvolume1) {
		Long old = this.sellvolume1;
		this.sellvolume1 = sellvolume1;
		this.emitter.firePropertyChange("sellvolume1", old, this.sellvolume1);
	}

	/**
	 * @return the buyprice1
	 */
	public Long getBuyprice1() {
		return buyprice1;
	}

	/**
	 * @param buyprice1 the buyprice1 to set
	 */
	public void setBuyprice1(Long buyprice1) {
		Long old = this.buyprice1;
		this.buyprice1 = buyprice1;
		this.emitter.firePropertyChange("buyprice1", old, this.buyprice1);
	}

	/**
	 * @return the marketvalue
	 */
	public Long getMarketvalue() {
		return marketvalue;
	}

	/**
	 * @param marketvalue the marketvalue to set
	 */
	public void setMarketvalue(Long marketvalue) {
		Long old = this.marketvalue;
		this.marketvalue = marketvalue;
		this.emitter.firePropertyChange("marketvalue", old, this.marketvalue);
	}

	/**
	 * @return the status
	 */
	public Long getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Long status) {
		Long old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		String old = this.code;
		this.code = code;
		this.emitter.firePropertyChange("code", old, this.code);
	}

	/**
	 * @return the averageprice
	 */
	public Long getAverageprice() {
		return averageprice;
	}

	/**
	 * @param averageprice the averageprice to set
	 */
	public void setAverageprice(Long averageprice) {
		Long old = this.averageprice;
		this.averageprice = averageprice;
		this.emitter.firePropertyChange("averageprice", old, this.averageprice);
	}

	/**
	 * @return the sellvolume4
	 */
	public Long getSellvolume4() {
		return sellvolume4;
	}

	/**
	 * @param sellvolume4 the sellvolume4 to set
	 */
	public void setSellvolume4(Long sellvolume4) {
		Long old = this.sellvolume4;
		this.sellvolume4 = sellvolume4;
		this.emitter.firePropertyChange("sellvolume4", old, this.sellvolume4);
	}

	/**
	 * @return the sellvolume5
	 */
	public Long getSellvolume5() {
		return sellvolume5;
	}

	/**
	 * @param sellvolume5 the sellvolume5 to set
	 */
	public void setSellvolume5(Long sellvolume5) {
		Long old = this.sellvolume5;
		this.sellvolume5 = sellvolume5;
		this.emitter.firePropertyChange("sellvolume5", old, this.sellvolume5);
	}

	/**
	 * @return the handrate
	 */
	public Long getHandrate() {
		return handrate;
	}

	/**
	 * @param handrate the handrate to set
	 */
	public void setHandrate(Long handrate) {
		Long old = this.handrate;
		this.handrate = handrate;
		this.emitter.firePropertyChange("handrate", old, this.handrate);
	}

	/**
	 * @return the ppjs
	 */
	public Long getPpjs() {
		return ppjs;
	}

	/**
	 * @param ppjs the ppjs to set
	 */
	public void setPpjs(Long ppjs) {
		Long old = this.ppjs;
		this.ppjs = ppjs;
		this.emitter.firePropertyChange("ppjs", old, this.ppjs);
	}

	/**
	 * @return the market
	 */
	public String getMarket() {
		return market;
	}

	/**
	 * @param market the market to set
	 */
	public void setMarket(String market) {
		String old = this.market;
		this.market = market;
		this.emitter.firePropertyChange("market", old, this.market);
	}

	/**
	 * @return the sellprice5
	 */
	public Long getSellprice5() {
		return sellprice5;
	}

	/**
	 * @param sellprice5 the sellprice5 to set
	 */
	public void setSellprice5(Long sellprice5) {
		Long old = this.sellprice5;
		this.sellprice5 = sellprice5;
		this.emitter.firePropertyChange("sellprice5", old, this.sellprice5);
	}

	/**
	 * @return the xdjs
	 */
	public Long getXdjs() {
		return xdjs;
	}

	/**
	 * @param xdjs the xdjs to set
	 */
	public void setXdjs(Long xdjs) {
		Long old = this.xdjs;
		this.xdjs = xdjs;
		this.emitter.firePropertyChange("xdjs", old, this.xdjs);
	}

	/**
	 * @return the sellprice3
	 */
	public Long getSellprice3() {
		return sellprice3;
	}

	/**
	 * @param sellprice3 the sellprice3 to set
	 */
	public void setSellprice3(Long sellprice3) {
		Long old = this.sellprice3;
		this.sellprice3 = sellprice3;
		this.emitter.firePropertyChange("sellprice3", old, this.sellprice3);
	}

	/**
	 * @return the buyvolume4
	 */
	public Long getBuyvolume4() {
		return buyvolume4;
	}

	/**
	 * @param buyvolume4 the buyvolume4 to set
	 */
	public void setBuyvolume4(Long buyvolume4) {
		Long old = this.buyvolume4;
		this.buyvolume4 = buyvolume4;
		this.emitter.firePropertyChange("buyvolume4", old, this.buyvolume4);
	}

	/**
	 * @return the newprice
	 */
	public Long getNewprice() {
		return newprice;
	}

	/**
	 * @param newprice the newprice to set
	 */
	public void setNewprice(Long newprice) {
		Long old = this.newprice;
		this.newprice = newprice;
		this.emitter.firePropertyChange("newprice", old, this.newprice);
	}

	/**
	 * @return the sellprice4
	 */
	public Long getSellprice4() {
		return sellprice4;
	}

	/**
	 * @param sellprice4 the sellprice4 to set
	 */
	public void setSellprice4(Long sellprice4) {
		Long old = this.sellprice4;
		this.sellprice4 = sellprice4;
		this.emitter.firePropertyChange("sellprice4", old, this.sellprice4);
	}

	/**
	 * @return the buyvolume5
	 */
	public Long getBuyvolume5() {
		return buyvolume5;
	}

	/**
	 * @param buyvolume5 the buyvolume5 to set
	 */
	public void setBuyvolume5(Long buyvolume5) {
		Long old = this.buyvolume5;
		this.buyvolume5 = buyvolume5;
		this.emitter.firePropertyChange("buyvolume5", old, this.buyvolume5);
	}

	/**
	 * @return the lb
	 */
	public Long getLb() {
		return lb;
	}

	/**
	 * @param lb the lb to set
	 */
	public void setLb(Long lb) {
		Long old = this.lb;
		this.lb = lb;
		this.emitter.firePropertyChange("lb", old, this.lb);
	}

	/**
	 * @return the secuamount
	 */
	public Long getSecuamount() {
		return secuamount;
	}

	/**
	 * @param secuamount the secuamount to set
	 */
	public void setSecuamount(Long secuamount) {
		Long old = this.secuamount;
		this.secuamount = secuamount;
		this.emitter.firePropertyChange("secuamount", old, this.secuamount);
	}

	/**
	 * @return the high
	 */
	public Long getHigh() {
		return high;
	}

	/**
	 * @param high the high to set
	 */
	public void setHigh(Long high) {
		Long old = this.high;
		this.high = high;
		this.emitter.firePropertyChange("high", old, this.high);
	}

	/**
	 * @return the sellprice1
	 */
	public Long getSellprice1() {
		return sellprice1;
	}

	/**
	 * @param sellprice1 the sellprice1 to set
	 */
	public void setSellprice1(Long sellprice1) {
		Long old = this.sellprice1;
		this.sellprice1 = sellprice1;
		this.emitter.firePropertyChange("sellprice1", old, this.sellprice1);
	}

	/**
	 * @return the low
	 */
	public Long getLow() {
		return low;
	}

	/**
	 * @param low the low to set
	 */
	public void setLow(Long low) {
		Long old = this.low;
		this.low = low;
		this.emitter.firePropertyChange("low", old, this.low);
	}

	/**
	 * @return the buyprice3
	 */
	public Long getBuyprice3() {
		return buyprice3;
	}

	/**
	 * @param buyprice3 the buyprice3 to set
	 */
	public void setBuyprice3(Long buyprice3) {
		Long old = this.buyprice3;
		this.buyprice3 = buyprice3;
		this.emitter.firePropertyChange("buyprice3", old, this.buyprice3);
	}

	/**
	 * @return the buyvolume2
	 */
	public Long getBuyvolume2() {
		return buyvolume2;
	}

	/**
	 * @param buyvolume2 the buyvolume2 to set
	 */
	public void setBuyvolume2(Long buyvolume2) {
		Long old = this.buyvolume2;
		this.buyvolume2 = buyvolume2;
		this.emitter.firePropertyChange("buyvolume2", old, this.buyvolume2);
	}

	/**
	 * @return the sellprice2
	 */
	public Long getSellprice2() {
		return sellprice2;
	}

	/**
	 * @param sellprice2 the sellprice2 to set
	 */
	public void setSellprice2(Long sellprice2) {
		Long old = this.sellprice2;
		this.sellprice2 = sellprice2;
		this.emitter.firePropertyChange("sellprice2", old, this.sellprice2);
	}

	/**
	 * @return the buyprice4
	 */
	public Long getBuyprice4() {
		return buyprice4;
	}

	/**
	 * @param buyprice4 the buyprice4 to set
	 */
	public void setBuyprice4(Long buyprice4) {
		Long old = this.buyprice4;
		this.buyprice4 = buyprice4;
		this.emitter.firePropertyChange("buyprice4", old, this.buyprice4);
	}

	/**
	 * @return the buyvolume3
	 */
	public Long getBuyvolume3() {
		return buyvolume3;
	}

	/**
	 * @param buyvolume3 the buyvolume3 to set
	 */
	public void setBuyvolume3(Long buyvolume3) {
		Long old = this.buyvolume3;
		this.buyvolume3 = buyvolume3;
		this.emitter.firePropertyChange("buyvolume3", old, this.buyvolume3);
	}

	/**
	 * @return the buyprice5
	 */
	public Long getBuyprice5() {
		return buyprice5;
	}

	/**
	 * @param buyprice5 the buyprice5 to set
	 */
	public void setBuyprice5(Long buyprice5) {
		Long old = this.buyprice5;
		this.buyprice5 = buyprice5;
		this.emitter.firePropertyChange("buyprice5", old, this.buyprice5);
	}

	/**
	 * @return the buyvolume1
	 */
	public Long getBuyvolume1() {
		return buyvolume1;
	}

	/**
	 * @param buyvolume1 the buyvolume1 to set
	 */
	public void setBuyvolume1(Long buyvolume1) {
		Long old = this.buyvolume1;
		this.buyvolume1 = buyvolume1;
		this.emitter.firePropertyChange("buyvolume1", old, this.buyvolume1);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "StockQuotationBean ["+
                "risefallrate=" + this.risefallrate +
                " , change=" + this.change +
                " , szjs=" + this.szjs +
                " , buysum=" + this.buysum +
                " , secuvolume=" + this.secuvolume +
                " , capital=" + this.capital +
                " , close=" + this.close +
                " , profitrate=" + this.profitrate +
                " , open=" + this.open +
                " , sellsum=" + this.sellsum +
                " , datetime=" + this.datetime +
                " , sellvolume2=" + this.sellvolume2 +
                " , sellvolume3=" + this.sellvolume3 +
                " , buyprice2=" + this.buyprice2 +
                " , sellvolume1=" + this.sellvolume1 +
                " , buyprice1=" + this.buyprice1 +
                " , marketvalue=" + this.marketvalue +
                " , status=" + this.status +
                " , code=" + this.code +
                " , averageprice=" + this.averageprice +
                " , sellvolume4=" + this.sellvolume4 +
                " , sellvolume5=" + this.sellvolume5 +
                " , handrate=" + this.handrate +
                " , ppjs=" + this.ppjs +
                " , market=" + this.market +
                " , sellprice5=" + this.sellprice5 +
                " , xdjs=" + this.xdjs +
                " , sellprice3=" + this.sellprice3 +
                " , buyvolume4=" + this.buyvolume4 +
                " , newprice=" + this.newprice +
                " , sellprice4=" + this.sellprice4 +
                " , buyvolume5=" + this.buyvolume5 +
                " , lb=" + this.lb +
                " , secuamount=" + this.secuamount +
                " , high=" + this.high +
                " , sellprice1=" + this.sellprice1 +
                " , low=" + this.low +
                " , buyprice3=" + this.buyprice3 +
                " , buyvolume2=" + this.buyvolume2 +
                " , sellprice2=" + this.sellprice2 +
                " , buyprice4=" + this.buyprice4 +
                " , buyvolume3=" + this.buyvolume3 +
                " , buyprice5=" + this.buyprice5 +
                " , buyvolume1=" + this.buyvolume1 +
        "]";
    }	

}
