/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class StockTradingOrderBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private Long amount;
	private Long currentPirce;
	private Long id;
	private String stockCode;
	private String status;
	private Long buy;
	private String stockName;
	private Long gainRate;
	private Long changeRate;
	private Long gain;
	private String marketCode;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	


	/**
	 * @return the amount
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Long amount) {
		Long old = this.amount;
		this.amount = amount;
		this.emitter.firePropertyChange("amount", old, this.amount);
	}

	/**
	 * @return the currentPirce
	 */
	public Long getCurrentPirce() {
		return currentPirce;
	}

	/**
	 * @param currentPirce the currentPirce to set
	 */
	public void setCurrentPirce(Long currentPirce) {
		Long old = this.currentPirce;
		this.currentPirce = currentPirce;
		this.emitter.firePropertyChange("currentPirce", old, this.currentPirce);
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		Long old = this.id;
		this.id = id;
		this.emitter.firePropertyChange("id", old, this.id);
	}

	/**
	 * @return the stockCode
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * @param stockCode the stockCode to set
	 */
	public void setStockCode(String stockCode) {
		String old = this.stockCode;
		this.stockCode = stockCode;
		this.emitter.firePropertyChange("stockCode", old, this.stockCode);
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		String old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the buy
	 */
	public Long getBuy() {
		return buy;
	}

	/**
	 * @param buy the buy to set
	 */
	public void setBuy(Long buy) {
		Long old = this.buy;
		this.buy = buy;
		this.emitter.firePropertyChange("buy", old, this.buy);
	}

	/**
	 * @return the stockName
	 */
	public String getStockName() {
		return stockName;
	}

	/**
	 * @param stockName the stockName to set
	 */
	public void setStockName(String stockName) {
		String old = this.stockName;
		this.stockName = stockName;
		this.emitter.firePropertyChange("stockName", old, this.stockName);
	}

	/**
	 * @return the gainRate
	 */
	public Long getGainRate() {
		return gainRate;
	}

	/**
	 * @param gainRate the gainRate to set
	 */
	public void setGainRate(Long gainRate) {
		Long old = this.gainRate;
		this.gainRate = gainRate;
		this.emitter.firePropertyChange("gainRate", old, this.gainRate);
	}

	/**
	 * @return the changeRate
	 */
	public Long getChangeRate() {
		return changeRate;
	}

	/**
	 * @param changeRate the changeRate to set
	 */
	public void setChangeRate(Long changeRate) {
		Long old = this.changeRate;
		this.changeRate = changeRate;
		this.emitter.firePropertyChange("changeRate", old, this.changeRate);
	}

	/**
	 * @return the gain
	 */
	public Long getGain() {
		return gain;
	}

	/**
	 * @param gain the gain to set
	 */
	public void setGain(Long gain) {
		Long old = this.gain;
		this.gain = gain;
		this.emitter.firePropertyChange("gain", old, this.gain);
	}

	/**
	 * @return the marketCode
	 */
	public String getMarketCode() {
		return marketCode;
	}

	/**
	 * @param marketCode the marketCode to set
	 */
	public void setMarketCode(String marketCode) {
		String old = this.marketCode;
		this.marketCode = marketCode;
		this.emitter.firePropertyChange("marketCode", old, this.marketCode);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "StockTradingOrderBean ["+
                "amount=" + this.amount +
                " , currentPirce=" + this.currentPirce +
                " , id=" + this.id +
                " , stockCode=" + this.stockCode +
                " , status=" + this.status +
                " , buy=" + this.buy +
                " , stockName=" + this.stockName +
                " , gainRate=" + this.gainRate +
                " , changeRate=" + this.changeRate +
                " , gain=" + this.gain +
                " , marketCode=" + this.marketCode +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((amount == null) ? 0 : amount.hashCode());
		result = prime * result + ((buy == null) ? 0 : buy.hashCode());
		result = prime * result
				+ ((changeRate == null) ? 0 : changeRate.hashCode());
		result = prime * result
				+ ((currentPirce == null) ? 0 : currentPirce.hashCode());
		result = prime * result + ((gain == null) ? 0 : gain.hashCode());
		result = prime * result
				+ ((gainRate == null) ? 0 : gainRate.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((marketCode == null) ? 0 : marketCode.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result
				+ ((stockCode == null) ? 0 : stockCode.hashCode());
		result = prime * result
				+ ((stockName == null) ? 0 : stockName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StockTradingOrderBean other = (StockTradingOrderBean) obj;
		if (amount == null) {
			if (other.amount != null)
				return false;
		} else if (!amount.equals(other.amount))
			return false;
		if (buy == null) {
			if (other.buy != null)
				return false;
		} else if (!buy.equals(other.buy))
			return false;
		if (changeRate == null) {
			if (other.changeRate != null)
				return false;
		} else if (!changeRate.equals(other.changeRate))
			return false;
		if (currentPirce == null) {
			if (other.currentPirce != null)
				return false;
		} else if (!currentPirce.equals(other.currentPirce))
			return false;
		if (gain == null) {
			if (other.gain != null)
				return false;
		} else if (!gain.equals(other.gain))
			return false;
		if (gainRate == null) {
			if (other.gainRate != null)
				return false;
		} else if (!gainRate.equals(other.gainRate))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (marketCode == null) {
			if (other.marketCode != null)
				return false;
		} else if (!marketCode.equals(other.marketCode))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (stockCode == null) {
			if (other.stockCode != null)
				return false;
		} else if (!stockCode.equals(other.stockCode))
			return false;
		if (stockName == null) {
			if (other.stockName != null)
				return false;
		} else if (!stockName.equals(other.stockName))
			return false;
		return true;
	}	

}
