/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class StockTaxisBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private Long profitrate;
	private Long risefallrate;
	private String market;
	private Long marketvalue;
	private String name;
	private Long newprice;
	private Long lb;
	private Long secuamount;
	private String code;
	private Long secuvolume;
	private Long handrate;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}


	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

	/**
	 * @return the profitrate
	 */
	public Long getProfitrate() {
		return profitrate;
	}

	/**
	 * @param profitrate the profitrate to set
	 */
	public void setProfitrate(Long profitrate) {
		Long old = this.profitrate;
		this.profitrate = profitrate;
		this.emitter.firePropertyChange("profitrate", old, this.profitrate);
	}

	/**
	 * @return the risefallrate
	 */
	public Long getRisefallrate() {
		return risefallrate;
	}

	/**
	 * @param risefallrate the risefallrate to set
	 */
	public void setRisefallrate(Long risefallrate) {
		Long old = this.risefallrate;
		this.risefallrate = risefallrate;
		this.emitter.firePropertyChange("risefallrate", old, this.risefallrate);
	}

	/**
	 * @return the market
	 */
	public String getMarket() {
		return market;
	}

	/**
	 * @param market the market to set
	 */
	public void setMarket(String market) {
		String old = this.market;
		this.market = market;
		this.emitter.firePropertyChange("market", old, this.market);
	}

	/**
	 * @return the marketvalue
	 */
	public Long getMarketvalue() {
		return marketvalue;
	}

	/**
	 * @param marketvalue the marketvalue to set
	 */
	public void setMarketvalue(Long marketvalue) {
		Long old = this.marketvalue;
		this.marketvalue = marketvalue;
		this.emitter.firePropertyChange("marketvalue", old, this.marketvalue);
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		String old = this.name;
		this.name = name;
		this.emitter.firePropertyChange("name", old, this.name);
	}

	/**
	 * @return the newprice
	 */
	public Long getNewprice() {
		return newprice;
	}

	/**
	 * @param newprice the newprice to set
	 */
	public void setNewprice(Long newprice) {
		Long old = this.newprice;
		this.newprice = newprice;
		this.emitter.firePropertyChange("newprice", old, this.newprice);
	}

	/**
	 * @return the lb
	 */
	public Long getLb() {
		return lb;
	}

	/**
	 * @param lb the lb to set
	 */
	public void setLb(Long lb) {
		Long old = this.lb;
		this.lb = lb;
		this.emitter.firePropertyChange("lb", old, this.lb);
	}

	/**
	 * @return the secuamount
	 */
	public Long getSecuamount() {
		return secuamount;
	}

	/**
	 * @param secuamount the secuamount to set
	 */
	public void setSecuamount(Long secuamount) {
		Long old = this.secuamount;
		this.secuamount = secuamount;
		this.emitter.firePropertyChange("secuamount", old, this.secuamount);
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		String old = this.code;
		this.code = code;
		this.emitter.firePropertyChange("code", old, this.code);
	}

	/**
	 * @return the secuvolume
	 */
	public Long getSecuvolume() {
		return secuvolume;
	}

	/**
	 * @param secuvolume the secuvolume to set
	 */
	public void setSecuvolume(Long secuvolume) {
		Long old = this.secuvolume;
		this.secuvolume = secuvolume;
		this.emitter.firePropertyChange("secuvolume", old, this.secuvolume);
	}

	/**
	 * @return the handrate
	 */
	public Long getHandrate() {
		return handrate;
	}

	/**
	 * @param handrate the handrate to set
	 */
	public void setHandrate(Long handrate) {
		Long old = this.handrate;
		this.handrate = handrate;
		this.emitter.firePropertyChange("handrate", old, this.handrate);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "StockTaxisBean ["+
                "profitrate=" + this.profitrate +
                " , risefallrate=" + this.risefallrate +
                " , market=" + this.market +
                " , marketvalue=" + this.marketvalue +
                " , name=" + this.name +
                " , newprice=" + this.newprice +
                " , lb=" + this.lb +
                " , secuamount=" + this.secuamount +
                " , code=" + this.code +
                " , secuvolume=" + this.secuvolume +
                " , handrate=" + this.handrate +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result
				+ ((handrate == null) ? 0 : handrate.hashCode());
		result = prime * result + ((lb == null) ? 0 : lb.hashCode());
		result = prime * result + ((market == null) ? 0 : market.hashCode());
		result = prime * result
				+ ((marketvalue == null) ? 0 : marketvalue.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((newprice == null) ? 0 : newprice.hashCode());
		result = prime * result
				+ ((profitrate == null) ? 0 : profitrate.hashCode());
		result = prime * result
				+ ((risefallrate == null) ? 0 : risefallrate.hashCode());
		result = prime * result
				+ ((secuamount == null) ? 0 : secuamount.hashCode());
		result = prime * result
				+ ((secuvolume == null) ? 0 : secuvolume.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StockTaxisBean other = (StockTaxisBean) obj;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (handrate == null) {
			if (other.handrate != null)
				return false;
		} else if (!handrate.equals(other.handrate))
			return false;
		if (lb == null) {
			if (other.lb != null)
				return false;
		} else if (!lb.equals(other.lb))
			return false;
		if (market == null) {
			if (other.market != null)
				return false;
		} else if (!market.equals(other.market))
			return false;
		if (marketvalue == null) {
			if (other.marketvalue != null)
				return false;
		} else if (!marketvalue.equals(other.marketvalue))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (newprice == null) {
			if (other.newprice != null)
				return false;
		} else if (!newprice.equals(other.newprice))
			return false;
		if (profitrate == null) {
			if (other.profitrate != null)
				return false;
		} else if (!profitrate.equals(other.profitrate))
			return false;
		if (risefallrate == null) {
			if (other.risefallrate != null)
				return false;
		} else if (!risefallrate.equals(other.risefallrate))
			return false;
		if (secuamount == null) {
			if (other.secuamount != null)
				return false;
		} else if (!secuamount.equals(other.secuamount))
			return false;
		if (secuvolume == null) {
			if (other.secuvolume != null)
				return false;
		} else if (!secuvolume.equals(other.secuvolume))
			return false;
		return true;
	}	

}
