/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class StockTaxisBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private Long profitrate;
	private Long risefallrate;
	private String market;
	private Long marketvalue;
	private String name;
	private Long newprice;
	private Long lb;
	private Long secuamount;
	private String code;
	private Long secuvolume;
	private Long handrate;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the profitrate
	 */
	public Long getProfitrate() {
		return profitrate;
	}

	/**
	 * @param profitrate the profitrate to set
	 */
	public void setProfitrate(Long profitrate) {
		Long old = this.profitrate;
		this.profitrate = profitrate;
		this.emitter.firePropertyChange("profitrate", old, this.profitrate);
	}

	/**
	 * @return the risefallrate
	 */
	public Long getRisefallrate() {
		return risefallrate;
	}

	/**
	 * @param risefallrate the risefallrate to set
	 */
	public void setRisefallrate(Long risefallrate) {
		Long old = this.risefallrate;
		this.risefallrate = risefallrate;
		this.emitter.firePropertyChange("risefallrate", old, this.risefallrate);
	}

	/**
	 * @return the market
	 */
	public String getMarket() {
		return market;
	}

	/**
	 * @param market the market to set
	 */
	public void setMarket(String market) {
		String old = this.market;
		this.market = market;
		this.emitter.firePropertyChange("market", old, this.market);
	}

	/**
	 * @return the marketvalue
	 */
	public Long getMarketvalue() {
		return marketvalue;
	}

	/**
	 * @param marketvalue the marketvalue to set
	 */
	public void setMarketvalue(Long marketvalue) {
		Long old = this.marketvalue;
		this.marketvalue = marketvalue;
		this.emitter.firePropertyChange("marketvalue", old, this.marketvalue);
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		String old = this.name;
		this.name = name;
		this.emitter.firePropertyChange("name", old, this.name);
	}

	/**
	 * @return the newprice
	 */
	public Long getNewprice() {
		return newprice;
	}

	/**
	 * @param newprice the newprice to set
	 */
	public void setNewprice(Long newprice) {
		Long old = this.newprice;
		this.newprice = newprice;
		this.emitter.firePropertyChange("newprice", old, this.newprice);
	}

	/**
	 * @return the lb
	 */
	public Long getLb() {
		return lb;
	}

	/**
	 * @param lb the lb to set
	 */
	public void setLb(Long lb) {
		Long old = this.lb;
		this.lb = lb;
		this.emitter.firePropertyChange("lb", old, this.lb);
	}

	/**
	 * @return the secuamount
	 */
	public Long getSecuamount() {
		return secuamount;
	}

	/**
	 * @param secuamount the secuamount to set
	 */
	public void setSecuamount(Long secuamount) {
		Long old = this.secuamount;
		this.secuamount = secuamount;
		this.emitter.firePropertyChange("secuamount", old, this.secuamount);
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		String old = this.code;
		this.code = code;
		this.emitter.firePropertyChange("code", old, this.code);
	}

	/**
	 * @return the secuvolume
	 */
	public Long getSecuvolume() {
		return secuvolume;
	}

	/**
	 * @param secuvolume the secuvolume to set
	 */
	public void setSecuvolume(Long secuvolume) {
		Long old = this.secuvolume;
		this.secuvolume = secuvolume;
		this.emitter.firePropertyChange("secuvolume", old, this.secuvolume);
	}

	/**
	 * @return the handrate
	 */
	public Long getHandrate() {
		return handrate;
	}

	/**
	 * @param handrate the handrate to set
	 */
	public void setHandrate(Long handrate) {
		Long old = this.handrate;
		this.handrate = handrate;
		this.emitter.firePropertyChange("handrate", old, this.handrate);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "StockTaxisBean ["+
                "profitrate=" + this.profitrate +
                " , risefallrate=" + this.risefallrate +
                " , market=" + this.market +
                " , marketvalue=" + this.marketvalue +
                " , name=" + this.name +
                " , newprice=" + this.newprice +
                " , lb=" + this.lb +
                " , secuamount=" + this.secuamount +
                " , code=" + this.code +
                " , secuvolume=" + this.secuvolume +
                " , handrate=" + this.handrate +
        "]";
    }	

}
