/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class StockMinuteLineBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String hqTime;
	private Long avgChangeRate;
	private Long avprice;
	private Long price;
	private Long secuamount;
	private Long secuvolume;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	


	/**
	 * @return the hqTime
	 */
	public String getHqTime() {
		return hqTime;
	}

	/**
	 * @param hqTime the hqTime to set
	 */
	public void setHqTime(String hqTime) {
		String old = this.hqTime;
		this.hqTime = hqTime;
		this.emitter.firePropertyChange("hqTime", old, this.hqTime);
	}

	/**
	 * @return the avgChangeRate
	 */
	public Long getAvgChangeRate() {
		return avgChangeRate;
	}

	/**
	 * @param avgChangeRate the avgChangeRate to set
	 */
	public void setAvgChangeRate(Long avgChangeRate) {
		Long old = this.avgChangeRate;
		this.avgChangeRate = avgChangeRate;
		this.emitter.firePropertyChange("avgChangeRate", old, this.avgChangeRate);
	}

	/**
	 * @return the avprice
	 */
	public Long getAvprice() {
		return avprice;
	}

	/**
	 * @param avprice the avprice to set
	 */
	public void setAvprice(Long avprice) {
		Long old = this.avprice;
		this.avprice = avprice;
		this.emitter.firePropertyChange("avprice", old, this.avprice);
	}

	/**
	 * @return the price
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * @param price the price to set
	 */
	public void setPrice(Long price) {
		Long old = this.price;
		this.price = price;
		this.emitter.firePropertyChange("price", old, this.price);
	}

	/**
	 * @return the secuamount
	 */
	public Long getSecuamount() {
		return secuamount;
	}

	/**
	 * @param secuamount the secuamount to set
	 */
	public void setSecuamount(Long secuamount) {
		Long old = this.secuamount;
		this.secuamount = secuamount;
		this.emitter.firePropertyChange("secuamount", old, this.secuamount);
	}

	/**
	 * @return the secuvolume
	 */
	public Long getSecuvolume() {
		return secuvolume;
	}

	/**
	 * @param secuvolume the secuvolume to set
	 */
	public void setSecuvolume(Long secuvolume) {
		Long old = this.secuvolume;
		this.secuvolume = secuvolume;
		this.emitter.firePropertyChange("secuvolume", old, this.secuvolume);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "StockMinuteLineBean ["+
                "hqTime=" + this.hqTime +
                " , avgChangeRate=" + this.avgChangeRate +
                " , avprice=" + this.avprice +
                " , price=" + this.price +
                " , secuamount=" + this.secuamount +
                " , secuvolume=" + this.secuvolume +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((avgChangeRate == null) ? 0 : avgChangeRate.hashCode());
		result = prime * result + ((avprice == null) ? 0 : avprice.hashCode());
		result = prime * result + ((hqTime == null) ? 0 : hqTime.hashCode());
		result = prime * result + ((price == null) ? 0 : price.hashCode());
		result = prime * result
				+ ((secuamount == null) ? 0 : secuamount.hashCode());
		result = prime * result
				+ ((secuvolume == null) ? 0 : secuvolume.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StockMinuteLineBean other = (StockMinuteLineBean) obj;
		if (avgChangeRate == null) {
			if (other.avgChangeRate != null)
				return false;
		} else if (!avgChangeRate.equals(other.avgChangeRate))
			return false;
		if (avprice == null) {
			if (other.avprice != null)
				return false;
		} else if (!avprice.equals(other.avprice))
			return false;
		if (hqTime == null) {
			if (other.hqTime != null)
				return false;
		} else if (!hqTime.equals(other.hqTime))
			return false;
		if (price == null) {
			if (other.price != null)
				return false;
		} else if (!price.equals(other.price))
			return false;
		if (secuamount == null) {
			if (other.secuamount != null)
				return false;
		} else if (!secuamount.equals(other.secuamount))
			return false;
		if (secuvolume == null) {
			if (other.secuvolume != null)
				return false;
		} else if (!secuvolume.equals(other.secuvolume))
			return false;
		return true;
	}	

}
