/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class TradingAccInfoBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean virtual;
	private String maxStockCode;
	private String over;
	private int status;
	private Long totalGain;
	private String maxStockMarket;
	private Long acctID;
	private Long sum;
	private long createDate;
	private String maxStockName;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the virtual
	 */
	public boolean getVirtual() {
		return virtual;
	}

	/**
	 * @param virtual the virtual to set
	 */
	public void setVirtual(boolean virtual) {
		boolean old = this.virtual;
		this.virtual = virtual;
		this.emitter.firePropertyChange("virtual", old, this.virtual);
	}

	/**
	 * @return the maxStockCode
	 */
	public String getMaxStockCode() {
		return maxStockCode;
	}

	/**
	 * @param maxStockCode the maxStockCode to set
	 */
	public void setMaxStockCode(String maxStockCode) {
		String old = this.maxStockCode;
		this.maxStockCode = maxStockCode;
		this.emitter.firePropertyChange("maxStockCode", old, this.maxStockCode);
	}

	/**
	 * @return the over
	 */
	public String getOver() {
		return over;
	}

	/**
	 * @param over the over to set
	 */
	public void setOver(String over) {
		String old = this.over;
		this.over = over;
		this.emitter.firePropertyChange("over", old, this.over);
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(int status) {
		int old = this.status;
		this.status = status;
		this.emitter.firePropertyChange("status", old, this.status);
	}

	/**
	 * @return the totalGain
	 */
	public Long getTotalGain() {
		return totalGain;
	}

	/**
	 * @param totalGain the totalGain to set
	 */
	public void setTotalGain(Long totalGain) {
		Long old = this.totalGain;
		this.totalGain = totalGain;
		this.emitter.firePropertyChange("totalGain", old, this.totalGain);
	}

	/**
	 * @return the maxStockMarket
	 */
	public String getMaxStockMarket() {
		return maxStockMarket;
	}

	/**
	 * @param maxStockMarket the maxStockMarket to set
	 */
	public void setMaxStockMarket(String maxStockMarket) {
		String old = this.maxStockMarket;
		this.maxStockMarket = maxStockMarket;
		this.emitter.firePropertyChange("maxStockMarket", old, this.maxStockMarket);
	}

	/**
	 * @return the acctID
	 */
	public Long getAcctID() {
		return acctID;
	}

	/**
	 * @param acctID the acctID to set
	 */
	public void setAcctID(Long acctID) {
		Long old = this.acctID;
		this.acctID = acctID;
		this.emitter.firePropertyChange("acctID", old, this.acctID);
	}

	/**
	 * @return the sum
	 */
	public Long getSum() {
		return sum;
	}

	/**
	 * @param sum the sum to set
	 */
	public void setSum(Long sum) {
		Long old = this.sum;
		this.sum = sum;
		this.emitter.firePropertyChange("sum", old, this.sum);
	}

	/**
	 * @return the createDate
	 */
	public long getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate the createDate to set
	 */
	public void setCreateDate(long createDate) {
		long old = this.createDate;
		this.createDate = createDate;
		this.emitter.firePropertyChange("createDate", old, this.createDate);
	}

	/**
	 * @return the maxStockName
	 */
	public String getMaxStockName() {
		return maxStockName;
	}

	/**
	 * @param maxStockName the maxStockName to set
	 */
	public void setMaxStockName(String maxStockName) {
		String old = this.maxStockName;
		this.maxStockName = maxStockName;
		this.emitter.firePropertyChange("maxStockName", old, this.maxStockName);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "TradingAccInfoBean ["+
                "virtual=" + this.virtual +
                " , maxStockCode=" + this.maxStockCode +
                " , over=" + this.over +
                " , status=" + this.status +
                " , totalGain=" + this.totalGain +
                " , maxStockMarket=" + this.maxStockMarket +
                " , acctID=" + this.acctID +
                " , sum=" + this.sum +
                " , createDate=" + this.createDate +
                " , maxStockName=" + this.maxStockName +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((acctID == null) ? 0 : acctID.hashCode());
		result = prime * result + (int) (createDate ^ (createDate >>> 32));
		result = prime * result
				+ ((maxStockCode == null) ? 0 : maxStockCode.hashCode());
		result = prime * result
				+ ((maxStockMarket == null) ? 0 : maxStockMarket.hashCode());
		result = prime * result
				+ ((maxStockName == null) ? 0 : maxStockName.hashCode());
		result = prime * result + ((over == null) ? 0 : over.hashCode());
		result = prime * result + status;
		result = prime * result + ((sum == null) ? 0 : sum.hashCode());
		result = prime * result
				+ ((totalGain == null) ? 0 : totalGain.hashCode());
		result = prime * result + (virtual ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TradingAccInfoBean other = (TradingAccInfoBean) obj;
		if (acctID == null) {
			if (other.acctID != null)
				return false;
		} else if (!acctID.equals(other.acctID))
			return false;
		if (createDate != other.createDate)
			return false;
		if (maxStockCode == null) {
			if (other.maxStockCode != null)
				return false;
		} else if (!maxStockCode.equals(other.maxStockCode))
			return false;
		if (maxStockMarket == null) {
			if (other.maxStockMarket != null)
				return false;
		} else if (!maxStockMarket.equals(other.maxStockMarket))
			return false;
		if (maxStockName == null) {
			if (other.maxStockName != null)
				return false;
		} else if (!maxStockName.equals(other.maxStockName))
			return false;
		if (over == null) {
			if (other.over != null)
				return false;
		} else if (!over.equals(other.over))
			return false;
		if (status != other.status)
			return false;
		if (sum == null) {
			if (other.sum != null)
				return false;
		} else if (!sum.equals(other.sum))
			return false;
		if (totalGain == null) {
			if (other.totalGain != null)
				return false;
		} else if (!totalGain.equals(other.totalGain))
			return false;
		if (virtual != other.virtual)
			return false;
		return true;
	}	

}
