/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class TradeDetailListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<TradeDetailBean> tradeDetails;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the tradeDetails
	 */
	public List<TradeDetailBean> getTradeDetails() {
		return tradeDetails;
	}

	/**
	 * @param tradeDetails the tradeDetails to set
	 */
	public void setTradeDetails(List<TradeDetailBean> tradeDetails) {
		List<TradeDetailBean> old = this.tradeDetails;
		this.tradeDetails = tradeDetails;
		if(this.tradeDetails != null){
            this.tradeDetails = new ListDecorator<TradeDetailBean>("tradeDetails", this.emitter,this.tradeDetails);
        }
		this.emitter.firePropertyChange("tradeDetails", old, this.tradeDetails);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "TradeDetailListBean ["+
                "tradeDetails=" + this.tradeDetails +
        "]";
    }	

}
