/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.bean.api.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.PropertyChangeListener;
import com.wxxr.mobile.core.bean.api.PropertyChangeSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class TradingAccountListBean implements IBindableBean {
	
	private final PropertyChangeSupport emitter = new PropertyChangeSupport(this);
	private List<GainBean> virtualTradingAccounts;
	private List<TradingAccInfoBean> t1TradingAccounts;
	private List<GainBean> successTradingAccounts;
	private List<GainBean> realTradingAccounts;
	private List<TradingAccInfoBean> t0TradingAccounts;
	private List<GainBean> allTradingAccounts;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void addPropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * @param propertyName
	 * @param listener
	 */
	public void removePropertyChangeListener(String propertyName,
			PropertyChangeListener listener) {
		emitter.removePropertyChangeListener(propertyName, listener);
	}


	/**
	 * @return the virtualTradingAccounts
	 */
	public List<GainBean> getVirtualTradingAccounts() {
		return virtualTradingAccounts;
	}

	/**
	 * @param virtualTradingAccounts the virtualTradingAccounts to set
	 */
	public void setVirtualTradingAccounts(List<GainBean> virtualTradingAccounts) {
		List<GainBean> old = this.virtualTradingAccounts;
		this.virtualTradingAccounts = virtualTradingAccounts;
		if(this.virtualTradingAccounts != null){
            this.virtualTradingAccounts = new ListDecorator<GainBean>("virtualTradingAccounts", this.emitter,this.virtualTradingAccounts);
        }
		this.emitter.firePropertyChange("virtualTradingAccounts", old, this.virtualTradingAccounts);
	}

	/**
	 * @return the t1TradingAccounts
	 */
	public List<TradingAccInfoBean> getT1TradingAccounts() {
		return t1TradingAccounts;
	}

	/**
	 * @param t1TradingAccounts the t1TradingAccounts to set
	 */
	public void setT1TradingAccounts(List<TradingAccInfoBean> t1TradingAccounts) {
		List<TradingAccInfoBean> old = this.t1TradingAccounts;
		this.t1TradingAccounts = t1TradingAccounts;
		if(this.t1TradingAccounts != null){
            this.t1TradingAccounts = new ListDecorator<TradingAccInfoBean>("t1TradingAccounts", this.emitter,this.t1TradingAccounts);
        }
		this.emitter.firePropertyChange("t1TradingAccounts", old, this.t1TradingAccounts);
	}

	/**
	 * @return the successTradingAccounts
	 */
	public List<GainBean> getSuccessTradingAccounts() {
		return successTradingAccounts;
	}

	/**
	 * @param successTradingAccounts the successTradingAccounts to set
	 */
	public void setSuccessTradingAccounts(List<GainBean> successTradingAccounts) {
		List<GainBean> old = this.successTradingAccounts;
		this.successTradingAccounts = successTradingAccounts;
		if(this.successTradingAccounts != null){
            this.successTradingAccounts = new ListDecorator<GainBean>("successTradingAccounts", this.emitter,this.successTradingAccounts);
        }
		this.emitter.firePropertyChange("successTradingAccounts", old, this.successTradingAccounts);
	}

	/**
	 * @return the realTradingAccounts
	 */
	public List<GainBean> getRealTradingAccounts() {
		return realTradingAccounts;
	}

	/**
	 * @param realTradingAccounts the realTradingAccounts to set
	 */
	public void setRealTradingAccounts(List<GainBean> realTradingAccounts) {
		List<GainBean> old = this.realTradingAccounts;
		this.realTradingAccounts = realTradingAccounts;
		if(this.realTradingAccounts != null){
            this.realTradingAccounts = new ListDecorator<GainBean>("realTradingAccounts", this.emitter,this.realTradingAccounts);
        }
		this.emitter.firePropertyChange("realTradingAccounts", old, this.realTradingAccounts);
	}

	/**
	 * @return the t0TradingAccounts
	 */
	public List<TradingAccInfoBean> getT0TradingAccounts() {
		return t0TradingAccounts;
	}

	/**
	 * @param t0TradingAccounts the t0TradingAccounts to set
	 */
	public void setT0TradingAccounts(List<TradingAccInfoBean> t0TradingAccounts) {
		List<TradingAccInfoBean> old = this.t0TradingAccounts;
		this.t0TradingAccounts = t0TradingAccounts;
		if(this.t0TradingAccounts != null){
            this.t0TradingAccounts = new ListDecorator<TradingAccInfoBean>("t0TradingAccounts", this.emitter,this.t0TradingAccounts);
        }
		this.emitter.firePropertyChange("t0TradingAccounts", old, this.t0TradingAccounts);
	}

	/**
	 * @return the allTradingAccounts
	 */
	public List<GainBean> getAllTradingAccounts() {
		return allTradingAccounts;
	}

	/**
	 * @param allTradingAccounts the allTradingAccounts to set
	 */
	public void setAllTradingAccounts(List<GainBean> allTradingAccounts) {
		List<GainBean> old = this.allTradingAccounts;
		this.allTradingAccounts = allTradingAccounts;
		if(this.allTradingAccounts != null){
            this.allTradingAccounts = new ListDecorator<GainBean>("allTradingAccounts", this.emitter,this.allTradingAccounts);
        }
		this.emitter.firePropertyChange("allTradingAccounts", old, this.allTradingAccounts);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "TradingAccountListBean ["+
                "virtualTradingAccounts=" + this.virtualTradingAccounts +
                " , t1TradingAccounts=" + this.t1TradingAccounts +
                " , successTradingAccounts=" + this.successTradingAccounts +
                " , realTradingAccounts=" + this.realTradingAccounts +
                " , t0TradingAccounts=" + this.t0TradingAccounts +
                " , allTradingAccounts=" + this.allTradingAccounts +
        "]";
    }	

}
