/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;
import com.wxxr.mobile.core.ui.common.ListDecorator;

/**
 * Generated by Bindable Bean generator
 *
 */
public class TradeDetailListBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private List<TradeDetailBean> tradeDetails;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}


	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

	/**
	 * @return the tradeDetails
	 */
	public List<TradeDetailBean> getTradeDetails() {
		return tradeDetails;
	}

	/**
	 * @param tradeDetails the tradeDetails to set
	 */
	public void setTradeDetails(List<TradeDetailBean> tradeDetails) {
		List<TradeDetailBean> old = this.tradeDetails;
		this.tradeDetails = tradeDetails;
		if(this.tradeDetails != null){
            this.tradeDetails = new ListDecorator<TradeDetailBean>("tradeDetails", this.emitter,this.tradeDetails);
        }
		this.emitter.firePropertyChange("tradeDetails", old, this.tradeDetails);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "TradeDetailListBean ["+
                "tradeDetails=" + this.tradeDetails +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((tradeDetails == null) ? 0 : tradeDetails.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TradeDetailListBean other = (TradeDetailListBean) obj;
		if (tradeDetails == null) {
			if (other.tradeDetails != null)
				return false;
		} else if (!tradeDetails.equals(other.tradeDetails))
			return false;
		return true;
	}	

}
