/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserAssetBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private long balance;
	private long usableBal;
	private long frozen;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the balance
	 */
	public long getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(long balance) {
		long old = this.balance;
		this.balance = balance;
		this.emitter.firePropertyChange("balance", old, this.balance);
	}

	/**
	 * @return the usableBal
	 */
	public long getUsableBal() {
		return usableBal;
	}

	/**
	 * @param usableBal the usableBal to set
	 */
	public void setUsableBal(long usableBal) {
		long old = this.usableBal;
		this.usableBal = usableBal;
		this.emitter.firePropertyChange("usableBal", old, this.usableBal);
	}

	/**
	 * @return the frozen
	 */
	public long getFrozen() {
		return frozen;
	}

	/**
	 * @param frozen the frozen to set
	 */
	public void setFrozen(long frozen) {
		long old = this.frozen;
		this.frozen = frozen;
		this.emitter.firePropertyChange("frozen", old, this.frozen);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserAssetBean ["+
                "balance=" + this.balance +
                " , usableBal=" + this.usableBal +
                " , frozen=" + this.frozen +
        "]";
    }	

}
