/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserCreateTradAccInfoBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private float deposit2;
	private float deposit3;
	private float rateData3;
	private float rateData2;
	private float voucherCostRate;
	private float deposit1;
	private String rateString;
	private Long maxAmount;
	private float costRate;
	private float rateData1;
	private String rateString2;
	private List<String> requestamount;
	private String rateString1;
	private String rateString3;
	private String userId;
	private float depositRate;
	private float capitalRate;
	
	
	//private float depositRate;//保证金比例
	//private float costRate;//综合费用比例,手续费
	private float costRateV;//模拟综合费用比例,手续费
	private float costRateT;//t综合费用比例,手续费
	private float costRateT3;//t3综合费用比例,手续费
	private float costRateTN;//t+n综合费用比例,手续费
	//private float capitalRate;//止损比例
	//private Long maxAmount;//可申请最大金额
	//private String rateString;//止损+保证金
	private String rateStringT;//t止损+保证金
	private String rateStringT3;//t3止损+保证金
	private String rateStringTN;//t+n止损+保证金
	private String rateStringV;//模拟止损+保证金
	//private float voucherCostRate;//实盘券综合费用比例,手续费

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}



	/**
	 * @return the deposit2
	 */
	public float getDeposit2() {
		return deposit2;
	}

	/**
	 * @param deposit2 the deposit2 to set
	 */
	public void setDeposit2(float deposit2) {
		float old = this.deposit2;
		this.deposit2 = deposit2;
		this.emitter.firePropertyChange("deposit2", old, this.deposit2);
	}

	/**
	 * @return the deposit3
	 */
	public float getDeposit3() {
		return deposit3;
	}

	/**
	 * @param deposit3 the deposit3 to set
	 */
	public void setDeposit3(float deposit3) {
		float old = this.deposit3;
		this.deposit3 = deposit3;
		this.emitter.firePropertyChange("deposit3", old, this.deposit3);
	}

	/**
	 * @return the rateData3
	 */
	public float getRateData3() {
		return rateData3;
	}

	/**
	 * @param rateData3 the rateData3 to set
	 */
	public void setRateData3(float rateData3) {
		float old = this.rateData3;
		this.rateData3 = rateData3;
		this.emitter.firePropertyChange("rateData3", old, this.rateData3);
	}

	/**
	 * @return the rateData2
	 */
	public float getRateData2() {
		return rateData2;
	}

	/**
	 * @param rateData2 the rateData2 to set
	 */
	public void setRateData2(float rateData2) {
		float old = this.rateData2;
		this.rateData2 = rateData2;
		this.emitter.firePropertyChange("rateData2", old, this.rateData2);
	}

	/**
	 * @return the voucherCostRate
	 */
	public float getVoucherCostRate() {
		return voucherCostRate;
	}

	/**
	 * @param voucherCostRate the voucherCostRate to set
	 */
	public void setVoucherCostRate(float voucherCostRate) {
		float old = this.voucherCostRate;
		this.voucherCostRate = voucherCostRate;
		this.emitter.firePropertyChange("voucherCostRate", old, this.voucherCostRate);
	}

	/**
	 * @return the deposit1
	 */
	public float getDeposit1() {
		return deposit1;
	}

	/**
	 * @param deposit1 the deposit1 to set
	 */
	public void setDeposit1(float deposit1) {
		float old = this.deposit1;
		this.deposit1 = deposit1;
		this.emitter.firePropertyChange("deposit1", old, this.deposit1);
	}

	/**
	 * @return the rateString
	 */
	public String getRateString() {
		return rateString;
	}

	/**
	 * @param rateString the rateString to set
	 */
	public void setRateString(String rateString) {
		String old = this.rateString;
		this.rateString = rateString;
		this.emitter.firePropertyChange("rateString", old, this.rateString);
	}

	/**
	 * @return the maxAmount
	 */
	public Long getMaxAmount() {
		return maxAmount;
	}

	/**
	 * @param maxAmount the maxAmount to set
	 */
	public void setMaxAmount(Long maxAmount) {
		Long old = this.maxAmount;
		this.maxAmount = maxAmount;
		this.emitter.firePropertyChange("maxAmount", old, this.maxAmount);
	}

	/**
	 * @return the costRate
	 */
	public float getCostRate() {
		return costRate;
	}

	/**
	 * @param costRate the costRate to set
	 */
	public void setCostRate(float costRate) {
		float old = this.costRate;
		this.costRate = costRate;
		this.emitter.firePropertyChange("costRate", old, this.costRate);
	}

	/**
	 * @return the rateData1
	 */
	public float getRateData1() {
		return rateData1;
	}

	/**
	 * @param rateData1 the rateData1 to set
	 */
	public void setRateData1(float rateData1) {
		float old = this.rateData1;
		this.rateData1 = rateData1;
		this.emitter.firePropertyChange("rateData1", old, this.rateData1);
	}

	/**
	 * @return the rateString2
	 */
	public String getRateString2() {
		return rateString2;
	}

	/**
	 * @param rateString2 the rateString2 to set
	 */
	public void setRateString2(String rateString2) {
		String old = this.rateString2;
		this.rateString2 = rateString2;
		this.emitter.firePropertyChange("rateString2", old, this.rateString2);
	}

	/**
	 * @return the requestamount
	 */
	public List<String> getRequestamount() {
		return requestamount;
	}

	/**
	 * @param requestamount the requestamount to set
	 */
	public void setRequestamount(List<String> requestamount) {
		List<String> old = this.requestamount;
		this.requestamount = requestamount;
		if(this.requestamount != null){
            this.requestamount = new ListDecorator<String>("requestamount", this.emitter,this.requestamount);
        }
		this.emitter.firePropertyChange("requestamount", old, this.requestamount);
	}

	/**
	 * @return the rateString1
	 */
	public String getRateString1() {
		return rateString1;
	}

	/**
	 * @param rateString1 the rateString1 to set
	 */
	public void setRateString1(String rateString1) {
		String old = this.rateString1;
		this.rateString1 = rateString1;
		this.emitter.firePropertyChange("rateString1", old, this.rateString1);
	}

	/**
	 * @return the rateString3
	 */
	public String getRateString3() {
		return rateString3;
	}

	/**
	 * @param rateString3 the rateString3 to set
	 */
	public void setRateString3(String rateString3) {
		String old = this.rateString3;
		this.rateString3 = rateString3;
		this.emitter.firePropertyChange("rateString3", old, this.rateString3);
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		String old = this.userId;
		this.userId = userId;
		this.emitter.firePropertyChange("userId", old, this.userId);
	}

	/**
	 * @return the depositRate
	 */
	public float getDepositRate() {
		return depositRate;
	}

	/**
	 * @param depositRate the depositRate to set
	 */
	public void setDepositRate(float depositRate) {
		float old = this.depositRate;
		this.depositRate = depositRate;
		this.emitter.firePropertyChange("depositRate", old, this.depositRate);
	}

	/**
	 * @return the capitalRate
	 */
	public float getCapitalRate() {
		return capitalRate;
	}

	/**
	 * @param capitalRate the capitalRate to set
	 */
	public void setCapitalRate(float capitalRate) {
		float old = this.capitalRate;
		this.capitalRate = capitalRate;
		this.emitter.firePropertyChange("capitalRate", old, this.capitalRate);
	}

    public float getCostRateV() {
		return costRateV;
	}

	public void setCostRateV(float costRateV) {
		this.costRateV = costRateV;
	}

	public float getCostRateT() {
		return costRateT;
	}

	public void setCostRateT(float costRateT) {
		this.costRateT = costRateT;
	}

	public float getCostRateT3() {
		return costRateT3;
	}

	public void setCostRateT3(float costRateT3) {
		this.costRateT3 = costRateT3;
	}

	public float getCostRateTN() {
		return costRateTN;
	}

	public void setCostRateTN(float costRateTN) {
		this.costRateTN = costRateTN;
	}

	public String getRateStringT() {
		return rateStringT;
	}

	public void setRateStringT(String rateStringT) {
		this.rateStringT = rateStringT;
	}

	public String getRateStringT3() {
		return rateStringT3;
	}

	public void setRateStringT3(String rateStringT3) {
		this.rateStringT3 = rateStringT3;
	}

	public String getRateStringTN() {
		return rateStringTN;
	}

	public void setRateStringTN(String rateStringTN) {
		this.rateStringTN = rateStringTN;
	}

	public String getRateStringV() {
		return rateStringV;
	}

	public void setRateStringV(String rateStringV) {
		this.rateStringV = rateStringV;
	}

	/* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserCreateTradAccInfoBean ["+
                "deposit2=" + this.deposit2 +
                " , deposit3=" + this.deposit3 +
                " , rateData3=" + this.rateData3 +
                " , rateData2=" + this.rateData2 +
                " , voucherCostRate=" + this.voucherCostRate +
                " , deposit1=" + this.deposit1 +
                " , rateString=" + this.rateString +
                " , maxAmount=" + this.maxAmount +
                " , costRate=" + this.costRate +
                " , rateData1=" + this.rateData1 +
                " , rateString2=" + this.rateString2 +
                " , requestamount=" + this.requestamount +
                " , rateString1=" + this.rateString1 +
                " , rateString3=" + this.rateString3 +
                " , userId=" + this.userId +
                " , depositRate=" + this.depositRate +
                " , capitalRate=" + this.capitalRate +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Float.floatToIntBits(capitalRate);
		result = prime * result + Float.floatToIntBits(costRate);
		result = prime * result + Float.floatToIntBits(deposit1);
		result = prime * result + Float.floatToIntBits(deposit2);
		result = prime * result + Float.floatToIntBits(deposit3);
		result = prime * result + Float.floatToIntBits(depositRate);
		result = prime * result
				+ ((maxAmount == null) ? 0 : maxAmount.hashCode());
		result = prime * result + Float.floatToIntBits(rateData1);
		result = prime * result + Float.floatToIntBits(rateData2);
		result = prime * result + Float.floatToIntBits(rateData3);
		result = prime * result
				+ ((rateString == null) ? 0 : rateString.hashCode());
		result = prime * result
				+ ((rateString1 == null) ? 0 : rateString1.hashCode());
		result = prime * result
				+ ((rateString2 == null) ? 0 : rateString2.hashCode());
		result = prime * result
				+ ((rateString3 == null) ? 0 : rateString3.hashCode());
		result = prime * result
				+ ((requestamount == null) ? 0 : requestamount.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		result = prime * result + Float.floatToIntBits(voucherCostRate);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserCreateTradAccInfoBean other = (UserCreateTradAccInfoBean) obj;
		if (Float.floatToIntBits(capitalRate) != Float
				.floatToIntBits(other.capitalRate))
			return false;
		if (Float.floatToIntBits(costRate) != Float
				.floatToIntBits(other.costRate))
			return false;
		if (Float.floatToIntBits(deposit1) != Float
				.floatToIntBits(other.deposit1))
			return false;
		if (Float.floatToIntBits(deposit2) != Float
				.floatToIntBits(other.deposit2))
			return false;
		if (Float.floatToIntBits(deposit3) != Float
				.floatToIntBits(other.deposit3))
			return false;
		if (Float.floatToIntBits(depositRate) != Float
				.floatToIntBits(other.depositRate))
			return false;
		if (maxAmount == null) {
			if (other.maxAmount != null)
				return false;
		} else if (!maxAmount.equals(other.maxAmount))
			return false;
		if (Float.floatToIntBits(rateData1) != Float
				.floatToIntBits(other.rateData1))
			return false;
		if (Float.floatToIntBits(rateData2) != Float
				.floatToIntBits(other.rateData2))
			return false;
		if (Float.floatToIntBits(rateData3) != Float
				.floatToIntBits(other.rateData3))
			return false;
		if (rateString == null) {
			if (other.rateString != null)
				return false;
		} else if (!rateString.equals(other.rateString))
			return false;
		if (rateString1 == null) {
			if (other.rateString1 != null)
				return false;
		} else if (!rateString1.equals(other.rateString1))
			return false;
		if (rateString2 == null) {
			if (other.rateString2 != null)
				return false;
		} else if (!rateString2.equals(other.rateString2))
			return false;
		if (rateString3 == null) {
			if (other.rateString3 != null)
				return false;
		} else if (!rateString3.equals(other.rateString3))
			return false;
		if (requestamount == null) {
			if (other.requestamount != null)
				return false;
		} else if (!requestamount.equals(other.requestamount))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		if (Float.floatToIntBits(voucherCostRate) != Float
				.floatToIntBits(other.voucherCostRate))
			return false;
		return true;
	}	

}
