/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.stock.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean messagePushSettingOn;
	private String userPic;
	private String unReadMsg;
	private boolean bindCard;
	private String score;
	private String totoalProfit;
	private String challengeShared;
	private String password;
	private String homeBack;
	private String joinShared;
	private String balance;
	private String username;
	private String phoneNumber;
	private String nickName;
	private boolean login;
	private String totoalScore;
	
	private boolean allowGuideGain = true;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}


	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return this.emitter.hasPropertyChangeListener(listener);
	}	

	/**
	 * @return the messagePushSettingOn
	 */
	public boolean getMessagePushSettingOn() {
		return messagePushSettingOn;
	}

	/**
	 * @param messagePushSettingOn the messagePushSettingOn to set
	 */
	public void setMessagePushSettingOn(boolean messagePushSettingOn) {
		boolean old = this.messagePushSettingOn;
		this.messagePushSettingOn = messagePushSettingOn;
		this.emitter.firePropertyChange("messagePushSettingOn", old, this.messagePushSettingOn);
	}

	public boolean getAllowGuideGain() {
		return allowGuideGain;
	}

	public void setAllowGuideGain(boolean allowGuideGain) {
		boolean old = this.allowGuideGain;
		this.allowGuideGain = allowGuideGain;
		this.emitter.firePropertyChange("allowGuideGain", old, this.allowGuideGain);
	}

	/**
	 * @return the userPic
	 */
	public String getUserPic() {
		return userPic;
	}

	/**
	 * @param userPic the userPic to set
	 */
	public void setUserPic(String userPic) {
		String old = this.userPic;
		this.userPic = userPic;
		this.emitter.firePropertyChange("userPic", old, this.userPic);
	}

	/**
	 * @return the unReadMsg
	 */
	public String getUnReadMsg() {
		return unReadMsg;
	}

	/**
	 * @param unReadMsg the unReadMsg to set
	 */
	public void setUnReadMsg(String unReadMsg) {
		String old = this.unReadMsg;
		this.unReadMsg = unReadMsg;
		this.emitter.firePropertyChange("unReadMsg", old, this.unReadMsg);
	}

	/**
	 * @return the bindCard
	 */
	public boolean getBindCard() {
		return bindCard;
	}

	/**
	 * @param bindCard the bindCard to set
	 */
	public void setBindCard(boolean bindCard) {
		boolean old = this.bindCard;
		this.bindCard = bindCard;
		this.emitter.firePropertyChange("bindCard", old, this.bindCard);
	}

	/**
	 * @return the score
	 */
	public String getScore() {
		return score;
	}

	/**
	 * @param score the score to set
	 */
	public void setScore(String score) {
		String old = this.score;
		this.score = score;
		this.emitter.firePropertyChange("score", old, this.score);
	}

	/**
	 * @return the totoalProfit
	 */
	public String getTotoalProfit() {
		return totoalProfit;
	}

	/**
	 * @param totoalProfit the totoalProfit to set
	 */
	public void setTotoalProfit(String totoalProfit) {
		String old = this.totoalProfit;
		this.totoalProfit = totoalProfit;
		this.emitter.firePropertyChange("totoalProfit", old, this.totoalProfit);
	}

	/**
	 * @return the challengeShared
	 */
	public String getChallengeShared() {
		return challengeShared;
	}

	/**
	 * @param challengeShared the challengeShared to set
	 */
	public void setChallengeShared(String challengeShared) {
		String old = this.challengeShared;
		this.challengeShared = challengeShared;
		this.emitter.firePropertyChange("challengeShared", old, this.challengeShared);
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		String old = this.password;
		this.password = password;
		this.emitter.firePropertyChange("password", old, this.password);
	}

	/**
	 * @return the homeBack
	 */
	public String getHomeBack() {
		return homeBack;
	}

	/**
	 * @param homeBack the homeBack to set
	 */
	public void setHomeBack(String homeBack) {
		String old = this.homeBack;
		this.homeBack = homeBack;
		this.emitter.firePropertyChange("homeBack", old, this.homeBack);
	}

	/**
	 * @return the joinShared
	 */
	public String getJoinShared() {
		return joinShared;
	}

	/**
	 * @param joinShared the joinShared to set
	 */
	public void setJoinShared(String joinShared) {
		String old = this.joinShared;
		this.joinShared = joinShared;
		this.emitter.firePropertyChange("joinShared", old, this.joinShared);
	}

	/**
	 * @return the balance
	 */
	public String getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(String balance) {
		String old = this.balance;
		this.balance = balance;
		this.emitter.firePropertyChange("balance", old, this.balance);
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		String old = this.username;
		this.username = username;
		this.emitter.firePropertyChange("username", old, this.username);
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		String old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the login
	 */
	public boolean getLogin() {
		return login;
	}

	/**
	 * @param login the login to set
	 */
	public void setLogin(boolean login) {
		boolean old = this.login;
		this.login = login;
		this.emitter.firePropertyChange("login", old, this.login);
	}

	/**
	 * @return the totoalScore
	 */
	public String getTotoalScore() {
		return totoalScore;
	}

	/**
	 * @param totoalScore the totoalScore to set
	 */
	public void setTotoalScore(String totoalScore) {
		String old = this.totoalScore;
		this.totoalScore = totoalScore;
		this.emitter.firePropertyChange("totoalScore", old, this.totoalScore);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserBean ["+
                "messagePushSettingOn=" + this.messagePushSettingOn +
                " , userPic=" + this.userPic +
                " , unReadMsg=" + this.unReadMsg +
                " , bindCard=" + this.bindCard +
                " , score=" + this.score +
                " , totoalProfit=" + this.totoalProfit +
                " , challengeShared=" + this.challengeShared +
                //" , password=" + this.password +
                " , homeBack=" + this.homeBack +
                " , joinShared=" + this.joinShared +
                " , balance=" + this.balance +
                " , username=" + this.username +
                " , phoneNumber=" + this.phoneNumber +
                " , nickName=" + this.nickName +
                " , login=" + this.login +
                " , totoalScore=" + this.totoalScore +
        "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((balance == null) ? 0 : balance.hashCode());
		result = prime * result + (bindCard ? 1231 : 1237);
		result = prime * result
				+ ((challengeShared == null) ? 0 : challengeShared.hashCode());
		result = prime * result
				+ ((homeBack == null) ? 0 : homeBack.hashCode());
		result = prime * result
				+ ((joinShared == null) ? 0 : joinShared.hashCode());
		result = prime * result + (login ? 1231 : 1237);
		result = prime * result + (messagePushSettingOn ? 1231 : 1237);
		result = prime * result
				+ ((nickName == null) ? 0 : nickName.hashCode());
		result = prime * result
				+ ((password == null) ? 0 : password.hashCode());
		result = prime * result
				+ ((phoneNumber == null) ? 0 : phoneNumber.hashCode());
		result = prime * result + ((score == null) ? 0 : score.hashCode());
		result = prime * result
				+ ((totoalProfit == null) ? 0 : totoalProfit.hashCode());
		result = prime * result
				+ ((totoalScore == null) ? 0 : totoalScore.hashCode());
		result = prime * result
				+ ((unReadMsg == null) ? 0 : unReadMsg.hashCode());
		result = prime * result + ((userPic == null) ? 0 : userPic.hashCode());
		result = prime * result
				+ ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserBean other = (UserBean) obj;
		if (balance == null) {
			if (other.balance != null)
				return false;
		} else if (!balance.equals(other.balance))
			return false;
		if (bindCard != other.bindCard)
			return false;
		if (challengeShared == null) {
			if (other.challengeShared != null)
				return false;
		} else if (!challengeShared.equals(other.challengeShared))
			return false;
		if (homeBack == null) {
			if (other.homeBack != null)
				return false;
		} else if (!homeBack.equals(other.homeBack))
			return false;
		if (joinShared == null) {
			if (other.joinShared != null)
				return false;
		} else if (!joinShared.equals(other.joinShared))
			return false;
		if (login != other.login)
			return false;
		if (messagePushSettingOn != other.messagePushSettingOn)
			return false;
		if (nickName == null) {
			if (other.nickName != null)
				return false;
		} else if (!nickName.equals(other.nickName))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (phoneNumber == null) {
			if (other.phoneNumber != null)
				return false;
		} else if (!phoneNumber.equals(other.phoneNumber))
			return false;
		if (score == null) {
			if (other.score != null)
				return false;
		} else if (!score.equals(other.score))
			return false;
		if (totoalProfit == null) {
			if (other.totoalProfit != null)
				return false;
		} else if (!totoalProfit.equals(other.totoalProfit))
			return false;
		if (totoalScore == null) {
			if (other.totoalScore != null)
				return false;
		} else if (!totoalScore.equals(other.totoalScore))
			return false;
		if (unReadMsg == null) {
			if (other.unReadMsg != null)
				return false;
		} else if (!unReadMsg.equals(other.unReadMsg))
			return false;
		if (userPic == null) {
			if (other.userPic != null)
				return false;
		} else if (!userPic.equals(other.userPic))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}	

}
